### ISSUE TITLE
default rules

### ISSUE THREAD

**Issue by orefalo** [maticzav/graphql-shield#100]
For authentication purposes, it's a pain to add a rule on every schema entity.

What about a default rule parameter?

**Comment by maticzav** [comment]
Hey @orefalo, is this in a way connected to #5? If so, you should be thrilled to hear we are launching a new version which will support this very soon!

**Comment by orefalo** [comment]
Actually.. it is ;-)

Do you need help on the new version, can I test?

I am currently hijacking your code to make it do what I want ;-)

Closing this, duplicate
