### ISSUE TITLE
Not Authorised Error even when i doesn't apply any rule to it.

### ISSUE THREAD

**Issue by nikunj321** [maticzav/graphql-shield#1132]
```js
const { shield, and, } = require('graphql-shield');
const { isAuthenticated, onlyCompany, onlyUser, ownJobOnly } = require('./authUtils');


module.exports = shield({
    Query: {
        user: and(isAuthenticated, onlyUser)
    },
    Mutation: {
        updateJob: and(isAuthenticated, onlyCompany, ownJobOnly),
        deleteJob: and(isAuthenticated, onlyCompany, ownJobOnly),
        createJob: and(isAuthenticated, onlyCompany),
    }
})
```
and myMutation is 
```graphql
mutation{
askQuestion(title: "any question", companyId: "flkjdsofiajwek" ) {
    id
    title
}
```
i got not authorised Error

**Comment by nikunj321** [comment]
i have create new Query 
```graphql
query searchQuestion($keyword: String!, $companyId: ID!) {
  searchQuestion(keyword: $keyword, companyId: $companyId) {
    title
  }
}
```

again same error

**Comment by maticzav** [comment]
Could you create a small reproduction codesandbox? This way I can help you more quickly.

**Comment by nikunj321** [comment]
https://github.com/nikunj321/findJob-server/tree/searchqs

**Comment by nikunj321** [comment]
Thanks mate for your time. it's not issue in Graphql-shield.
it's because of my resolver. some error was there but shows 'Not Authorised!' Error so i thought it's because of Graphql-shield

**Comment by maticzav** [comment]
Try setting `debug` option to `true`. This way `shield` won't mask internal errors.

> PS.: Feel free to Tweet about the response time on new issues in GraphQLShield 😉
