### ISSUE TITLE
How do you use debug mode?

### ISSUE THREAD

**Issue by waynetheisinger** [maticzav/graphql-shield#1137]
# Question about GraphQL Shield

I don't understand how to use the debug toggle - when I set it to true, the error returned when something fails validation is "Not Authorised!" where I would have expected a more verbose message telling me what type, field, query or mutation had failed to authenticate. What have I misunderstood?

- [x] I have checked other questions and found none that matches mine.

**Comment by waynetheisinger** [comment]
Don't worry I've found it `error.path` for others info - could possibly be a good addition to the docs

**Comment by maticzav** [comment]
Thank you for the suggestion. I am glad you've found the solution. Let me know if you need any help with this issue. If not, you can also close it.
