### ISSUE TITLE
Should throw 'ForbiddenError' error

### ISSUE THREAD

**Issue by develomark** [maticzav/graphql-shield#120]
Apollo Server 2.0 added the ability to add error codes. Out of the box there are three error code types:

* AuthenticationError — for authentication failures
* ForbiddenError — for authorization failures
* UserInputError — for validation errors on user input

I propose that graphql-shield should throw `ForbiddenError`. This results in a more meaningful, standardised response on the client.

from:
```json
extensions: { code :"INTERNAL_SERVER_ERROR" },
message: "Not Authorised!"
```

to:

```json
extensions: { code :"FORBIDDEN" },
message: "Not Authorised!"
```

ForbiddenError can be imported from apollo-server:
```javascript
import { ForbiddenError } from 'apollo-server'
```
____

I have a current workaround by setting `allowExternalErrors` to true and throwing this error from the rule resolver.

**Comment by maticzav** [comment]
This should get fixed with #119

**Comment by develomark** [comment]
Brilliant thanks @maticzav

**Comment by maticzav** [comment]
I’ll close this issue as it seems #119 will resolve it.

**Comment by almostprogrammer** [comment]
@marktani I cannot get this to work with Apollo Server v 2 and `graphql-shield` 3.2.4. Returning an error in the rule does not help. Here's what my rule looks like

```
const checkArgs = obj => rule()(async (parent, args, ctx) => {
  const argsMatch = Object.keys(obj)
    .every((key) => {
      const value = obj[key];
      let isMatch;
      switch (value.split('.')[0]) {
      case '$context': {
        isMatch = args[key] === deref(ctx, value.replace('$context.', ''));
        break;
      }
      default:
        isMatch = args[key] === value;
        break;
      }

      if (!isMatch) return new ForbiddenError('Access denied');
      return isMatch;
    });

  return argsMatch;
});
```
