### ISSUE TITLE
How to add a rule for a all List?

### ISSUE THREAD

**Issue by johannpinson** [maticzav/graphql-shield#122]
When I have a query which returns a list, if the first response is good, it's the same for all object in the list, ex:
```graphql
type Query {
  users: [User!]!
}
```

rules: 
```js
shield(
  {
    User: {
      email: isOwner
    }
  }
)
```

The rule is just for logic to check if the user authenticated is the same as the requested to allow the request to return the field.

I notice if I add a parameter to the query to change the order, the query is directly denied.

**Comment by johannpinson** [comment]
Hey @ryan-cat 
For information, I see with @maticzav and it was a `cache` problem that I had to change from `contextual` to `strict` to force the verification for all type (because my query returns a List).

For your second question, I invite you to create a specific issue.

**Comment by maticzav** [comment]
@johannpinson @ryan-cat, I am so happy to see the conversation going. I assume you have resolved the issue. Hence I'll close the issue. Please do reopen it if this is still active.
