### ISSUE TITLE
Fragment on another entity instead of parent one causes out of memory

### ISSUE THREAD

**Issue by kevrat** [maticzav/graphql-shield#166]
# Bug report

* [ x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

If my rule have fragment on Entity1 and i use it rule on Entity2 then i get infinity loop and out of memory as result

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

> (Delete the filler code and replace it with your own)

1. This is my GraphQL Schema. 

```graphql
type User implements Node {
  id: ID! @unique
}

type Competition implements Node {
  id: ID! @unique
  applications: [Application!]! @relation(name: "CompetitionApplication")
}

type Application implements Node {
  id: ID! @unique
  competition: Competition! @relation(name: "CompetitionApplication")
}
```

2. This is the invoked query

```graphql
{
  competitions{
    applications{
      id
    }
  }
}
```

3. I use these permissions

```ts
...
    Competition: {
      applications: rules.isOwnerOfCompetition,
    },
...
export const isOwnerOfCompetition = rule({
    cache: "strict",
    fragment: `fragment userID on User { id }`,
    })(
    async (
        parent,
        args,
        ctx: Context,
        info,
    ) => {
        console.log(info);
        return true;
    },
);
...

const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  resolverValidationOptions: {
    requireResolversForResolveType: false,
  },
  middlewares: [forwardMiddleware, permissions],
  context: ({
    request,
    response,
    fragmentReplacements: middlewareFragmentReplacements,
  }) => ({
    request,
    response,
    user: getUser(request),
    db: new Prisma({
      fragmentReplacements: [
        ...fragmentReplacements,
        ...middlewareFragmentReplacements,
      ],
      // typeDefs: 'src/generated/prisma.graphql', // the auto-generated GraphQL schema of the Prisma API
      endpoint: process.env.PRISMA_ENDPOINT,
      secret: process.env.PRISMA_SECRET, // only needed if specified in `database/prisma.yml`
      debug: false,
      // debug: process.env.NODE_ENV !== 'production'
    }),
  }),
});
```

4. This is the error I see

out of memory

## Expected behavior

Some error maybe

## Actual behaviour
Rule function is not executed and i get out of memory after infinity loop

## Additional context
If i change rule fragment to 

```ts
export const isOwnerOfCompetition = rule({
    cache: "strict",
    fragment: `fragment CompetitionID on Competition { id }`,
    })(
    async (
        parent,
        args,
        ctx: Context,
        info,
    ) => {
        console.log(info);
        return true;
    },
);
```
everything is work

**Comment by maticzav** [comment]
Hey 👋,

I love the question you possed, very fascinating. May I ask before we dive into solving it; why do you need `id` of the `User` in `Competition-related resolver?

**Comment by kevrat** [comment]
This is just for example. 
The main idea that I have many rules and time by time i forget that it rule use fragment, that use another entity.
part of my current rules:
```typescript

    Query: {
      // me: rules.isAuthenticated,
      // user: rules.isSelf
      competition: rules.isPublicCompetition,
      sportsman: rules.isTrainerOfSportsman
      // competitionApplications: rules.isOwnerOfCompetition
    },
    Mutation: {
      updateCompetition: or(rules.isOwnerOfCompetition),
      updateSportsman: rules.isTrainerOfSportsman,
      deleteSportsman: rules.isTrainerOfSportsman,
      updateUser: rules.isSelf,
      // createApplication: and(rules.isApplicationOnPublicCompetition, rules.isTrainerOfSportsmen, rules.isApplicationInAgeCategory),
      // updateApplication: and(
      //   rules.isApplicationOnPublicCompetition, rules.isTrainerOfSportsmen, rules.isApplicationInAgeCategory,
      //   or(rules.isOwnerOfApplication, rules.isOwnerOfCompetitionInApplication)
      // ),
      createApplication: and(
        rules.isApplicationOnPublicCompetition,
        rules.isTrainerOfSportsmen
      ),
      updateApplication: and(
        rules.isApplicationOnPublicCompetition,
        rules.isTrainerOfSportsmen,
        or(rules.isOwnerOfApplication, rules.isOwnerOfCompetitionInApplication)
      ),
      deleteApplication: or(
        rules.isOwnerOfApplication,
        rules.isOwnerOfCompetitionInApplication
      )
    },
    User: {
      id: allow,
      email: allow,
      emailvalidated: rules.isSelf,
      firstName: allow,
      lastName: allow,
      middleName: allow,
      phone: allow,
      // phone: rules.isSelf,
      country: allow,
      region: allow,
      city: allow,
      competitions: rules.isSelf,
      sportsmen: rules.isSelf
      // applications: allow, // rules in Action
    },
    // Action: or(
    //   rules.isOwnerOfApplication,
    //   rules.isOwnerOfCompetitionInApplication,
    //   not(rules.isActionExist),
    //   // rules.hasAccessToCompetitionApplicaton(["VIEW"]),
    // ),
    Competition: {
      id: allow,
      name: allow,
      city: allow,
      country: allow,
      region: allow,
      dateStart: allow,
      dateEnd: allow,
      description: allow,
      owner: allow,
      state: allow,
      logoUrl: allow,
      imageUrl: allow,
      documents: allow,
      applications: or(
        rules.isOwnerOfCompetition,
        rules.hasAccessToCompetition(['VIEW'])
      )
    }
  },
```
(Attached code is terrible, so i think about of full refactoring of rules logic since i'm start using fragments)

This is definitely not a critical issue. But it is very confusing, if after some changes in the rules, everything suddenly gets stuck without any error.
Just to say that I think this problem should be more pronounced (print some error and don't cause out of memory).
Unless, of course, everything is so, and I have not missed anything.

**Comment by maticzav** [comment]
OK, let's dwell on this issue for a bit more time. First and foremost, the problem which you are experiencing is connected with `graphql-tools`, not `graphql-shield` itself. Nevertheless, it's high time someone fixed this, and it's probably going to be one of us anyhow.

I believe that this problem occurs because of the reference loop in the `ReplaceFieldWithFragment` transformer function. I am quite surprised no one has yet stumbled upon the problem that if your rule relies on `fragment Fragment on X { id }` and you apply it to entire type, which includes `id` as well, querying `id` breaks the chain as you described it, and results in a memory leak.

However, I see that you've found a different kind of a problem that I wasn't aware of beforehand. That's also the reason why I asked the previous question. If you could help me parallelise your problem with the one I described above, we could put together a solution proposal.

Have you by chance thought about what might be the nucleus of your problem? 🙂
