### ISSUE TITLE
Custom error message

### ISSUE THREAD

**Issue by jhnferraris** [maticzav/graphql-shield#17]
Is it possible to modify the `error` object?

```
{
  "data": null,
  "errors": [
    {
      "message": "Insufficient Permissions.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getSurveys"
      ]
    }
  ]
}
```

Or can we directly use other error handler like [apollo-errors](https://github.com/thebigredgeek/apollo-errors) instead of using the default "Insufficient permission"

Thanks for the assist!

**Comment by maticzav** [comment]
@jhnferraris custom errors are currently not supported, but I would love to hear more from you on this topic. Could you add this to `roadmap` thread? 🙂 

#6

**Comment by dakshshah96** [comment]
@maticzav Any updates on this? I really want my developers to know what the cause of the error is. For example, `JWT token has expired` or something like `Authorization header is required` instead of just `Insufficient Permissions.`.

**Comment by jhnferraris** [comment]
@dakshshah96 

Since it is still in their roadmap, we opted on using a different approach. We used [graphql-resolvers](https://github.com/lucasconstantino/graphql-resolvers)'s, `combineResolvers`. In which we have one resolver doing the "validation" and throw custom error when the validation fails.

**Comment by dakshshah96** [comment]
@jhnferraris If it's not too much trouble, can you give me an example of how custom errors can be implemented? I've already defined all of my schema using `graphql-tools` in my `apollo-server` powered GraphQL backend. Thanks!

**Comment by jhnferraris** [comment]
@dakshshah96 Sure!

Example you have a "validation" resolver:

Resolver A: `validateAuthObject`

```
const { AuthorizationError } = require("../../errors"); // -- This is an instance of `apollo-errors`
module.exports = async (root, args, context, info) => {
  const user = _.get(args, "user", null);
  if (!user) {
    throw new AuthorizationError({
      message: "Missing user object.",
    });
  }
};

```

In your main resolver of a certain GraphQL query, let say `getData(user: User, options: JSON!)`. We combine our `validateUserObject` and the "main" resolver. 

```
const { combineResolvers } = require("graphql-resolvers");

getData: combineResolvers(validateUserObject, async (obj, args, context, info) => {
      const options = _.get(args, "options", {});
      return DataRepository.getAll(options);
    }),

```

Once `user` is `null` it will return 

```
{
  "data": null,
  "errors": [
    {
      "message": "Missing user object.",
      "name": "AuthorizationError",
      "time_thrown": "2018-03-22T10:48:42.113Z",
      "data": {
        "code": "auth-1"
      }
    }
  ]

}
```

I hope this helps. :)
