### ISSUE TITLE
[Feature] Use rules with fragments

### ISSUE THREAD

**Issue by melkir** [maticzav/graphql-shield#173]
According to the Prisma Middleware API available here https://github.com/prisma/graphql-middleware#api we can use an array of fragments `fragments?: IMiddlewareFragment[]`

I would like to be able to do the same thing using `graphql-shield`.
For exemple:
```js
rule({
  fragments: ['... on User { country }', '... on Employee { country }']
})
```

**Comment by maticzav** [comment]
Hey @melkir,

`fragments` API in middleware is primarily used for easier fragments management inside the middleware itself. `graphql-shield`, for example, uses `fragments` to handle logic rules which combine multiple rule-fragments into one. Nevertheless, `fragments` inside one "chunk" should carry the same type identifier and could be rewritten as a single fragment.

I think your suggestion could still work, but I am not 100% sure. Maybe you could make some tests or even compose a PR. Knowing that `ApolloServer` (`graphql-tools`) doesn't support multiple fragments per resolver could be a con to the argument, but thinking about it now makes total sense to include the option in the rule definition.

**Comment by maticzav** [comment]
Might be connected with #166
