### ISSUE TITLE
Support for graphql-middleware v2?

### ISSUE THREAD

**Issue by carstenbaumhoegger** [maticzav/graphql-shield#181]
# Explain your question

* [x] I have checked existing issue and found none that could answer my question.

First of all: Thanks for this great project! We're using it heavily in one of our products and it's really doing a great job at managing the accessibility of our resolvers!

`graphql-middleware v2` came out a few days ago and supports `graphql v14`. Is the support for `graphql-middleware v2` planned for the near future?

**Comment by carstenbaumhoegger** [comment]
Just noticed the release of https://github.com/maticzav/graphql-shield/releases/tag/v4.0.0

Thanks for the fast release, keep up the great work!

**Comment by maticzav** [comment]
@carstenbaumhoegger thanks! Note that you might have to update to `4.0.1` as `4.0.0` doesn't yet include `graphql` v14 `graphql-tools`. I'll add integration tests to make sure such updates don't get away unnoticed. Could you open an issue if you find any errors as well? 🙂

**Comment by carstenbaumhoegger** [comment]
I've already updated to `4.0.1`. I'll open a new issue if I find anything but everything is working as expected in the first few hours 🎉
