### ISSUE TITLE
Apollo-server 2.0 setup

### ISSUE THREAD

**Issue by donedgardo** [maticzav/graphql-shield#183]
# Question about GraphQL Shield

I'm transitioning to use apollo-server instead of graphql yoga. I don't know how to implement graphql shield permisions middlewares into apollo-server 2.0, are there any examples?

I saw there was one with apollo-server-lambda but im not sure how to do it if i would use the express version.

* [x] I have checked other questions and found none that macthes mine.

**Comment by donedgardo** [comment]
👍 Awsome!
Will share my solution.
https://gist.github.com/donedgardo/ed2d36f6e650991543e5a55c77cddc0d

**Comment by maticzav** [comment]
Thanks for sharing! Let me know if you need any help with anything else 🙂.

**Comment by doitadrian** [comment]
I was also in the similar situation, wanted to connect `graphql-shield` with `apollo-server-lambda`, but couldn't find a clear example.

After a few tries, I managed to connect everything via `graphql-middleware`. I put an example here: https://github.com/doitadrian/example-graphql-shield-apollo-server-lambda

Hope it helps 🙂

**Comment by maticzav** [comment]
@doitadrian this is perfect! Would you mind if I add it to the `examples` section?

**Comment by doitadrian** [comment]
Be my guest :) @maticzav
