### ISSUE TITLE
Cache permissions on the same resolver level

### ISSUE THREAD

**Issue by nickluger** [maticzav/graphql-shield#19]
It seems permissions are only cached when the father ran the same permission function before.
If i want to simply hide a set of fields, for unauthorized users, caching for siblings would come in handy.
like this:

```ts
export const userProfilePermissions = {
  // isOwnProfile is run 3 x currently
  email: isOwnProfile,
  phone: isOwnProfile,
  address: isOwnProfile
}
```

**Comment by maticzav** [comment]
I agree, this would be a really cool feature! I’ll add it in #6
