### ISSUE TITLE
A way to return data even if one of the query fails?

### ISSUE THREAD

**Issue by johhansantana** [maticzav/graphql-shield#195]
# Question about GraphQL Shield

Was wondering, if we have a query like this:
```
{
  posts {
    id
  }
  users {
    email
  }
}
```

and we allow the public to view posts but only admins to view `users`, I expect the `posts` query to return data but the `users` one to throw an error.

But right now it just returns an error and doesn't return data on `posts`.

Is there a workaround on this or this is intentional?

* [x] I have checked other questions and found none that macthes mine.

**Comment by johhansantana** [comment]
Not using a `fallbackRule`.

Shield permission would look like this:

```graphql
export default shield({
  Query: {
    users: isAdmin
  }
}
```

since `posts` is public

and the `isAdmin` would be this:

```typescript
export const isAdmin = rule()(async (parent, args, ctx, info) => {
  const userId = getUserId(ctx);
  const user = await db.user({ id: userId });
  return user.role === "ADMIN";
});
```

**Comment by maticzav** [comment]
@johhansantana that's an interesting question! 

Would you mind sharing the portion of `schema` concerning the error and `query` you are using to obtain the desired data? I have an urge that this might be connected to https://github.com/maticzav/graphql-shield/issues/97#issuecomment-404867307

Let me know if that fixed your problem! 🙂

**Comment by johhansantana** [comment]
@maticzav I just notice that it returns data for the allowed queries in the sandbox/playground but when using apollo-client in the app using the exact query, the `data` returns undefined when it errors out 🤔 

I think it has nothing to do with graphql-shield, though, your post really helped me understand much more.

Thanks!

**Comment by johhansantana** [comment]
I created an issue in the apollo-react repository in case you want to take a look:
https://github.com/apollographql/react-apollo/issues/2584

**Comment by maticzav** [comment]
Oh great! I think this might be useful as well https://www.apollographql.com/docs/react/features/error-handling.html#policies

**Comment by johhansantana** [comment]
oh, so it wasn't a bug, just a configuration that was not set 😭 Sorry for the noise and thanks again!
