### ISSUE TITLE
Is there a restriction on permission names,  regarding cacheability?

### ISSUE THREAD

**Issue by nickluger** [maticzav/graphql-shield#20]
is there a restriction on naming permissions that should be documented? https://github.com/maticzav/graphql-shield/blob/0a9c4726d7675db801f87bd5da6a5ff85ac9be69/src/index.ts#L133

**Comment by maticzav** [comment]
@nickluger no, there’s no restrictions to permission name - as far as they don’t have the same name as field they are restricting.

I’ll add this to the docs, thanks for pointing it out! 🙂
