### ISSUE TITLE
Having issues wrapping middleware around schema, with applyMiddleware

### ISSUE THREAD

**Issue by OGNeutron** [maticzav/graphql-shield#216]
Error: The introspection query is resolving asynchronously; execution of an introspection query is not expected to return a `Promise`.

Wrapped type resolvers should maintain the existing execution dynamics of the resolvers they wrap (i.e. async vs sync) or introspection types should be excluded from wrapping by checking them with `graphql/type`s, `isIntrospectionType` predicate function prior to wrapping.

Here is the resolver and middleware in question 

```
import { rule, shield } from 'graphql-shield';
import { Context } from '../../../tstypes';

const isAuthenticated = rule()(
	async (_: any, __: any, { session }: Context, ___: any) => !!session.userId
);

export const ShieldMiddleware = shield(
	{
		Query: {
			getProfile: isAuthenticated
		}
	},
	{
		debug: true,
		graphiql: true
	}
);
```

```
async getProfile(
			_: any,
			{ username }: any,
			{ db }: Context,
			info: any
		) {
			try {
				console.log('PROFILE');
				const profile: User | null = await db.query.user(
					{ where: { username } },
					info
				);

				if (!profile) {
					return new ApolloError('No such user');
				}

				console.log('PROFILE', profile);

				return profile;
			} catch (error) {
				logger.error({ level: '5', message: error });
				return error;
			}
		}
```

And I am using apollo-express-server.

**Comment by maticzav** [comment]
Hey @OGNeutron 👋,

could you use one of the templates for creating an issue? For the reference, I believe this is connected to prisma/graphql-middleware#75 and apollographql/apollo-server#1935

**Comment by OGNeutron** [comment]
I created a new issue using one of the templates.
