### ISSUE TITLE
Add authorization on a single field

### ISSUE THREAD

**Issue by alan345** [maticzav/graphql-shield#239]
Hey! Thanks for this great repo
I could not find in the documentation if we could add an authorization on a single field. Example: 

Schema:
```
type Customer {
  id: ID! @unique
  email: String! @unique
  moreDetailsAboutUserForAdmins: String #need to hide this field for non-Admins
  products: [Product!]!
}

type Product {
  id: ID! @unique
  name: String!
  price: Int!
  users: [User!]!
}
```

On the front end, I am doing this request:
```
users {
  id
  moreDetailsForAdmins
}
```
How can I show `moreDetailsAboutUserForAdmins` only for the Admins? In resolver of `users`? fine.
Now if I do this query:

```
products {
  id
  name
  users {
    id
    moreDetailsAboutUserForAdmins
  }
}
```
Do have I to also do this control in the resolver of `products`?

Is there a way to handle it with shield in a more scalable way?
Thanks!
(related topic https://www.prisma.io/forum/t/graphql-security-protect-nested-data/4519)

**Comment by maticzav** [comment]
Hey 👋,

Indeed, you can add authorisation to a single field; make it field specific!

```ts
const permissions = shield({
  Query: {
    frontPage: not(isAuthenticated),
    fruits: and(isAuthenticated, or(isAdmin, isEditor)),
    customers: and(isAuthenticated, isAdmin),
  },
  Mutation: {
    addFruitToBasket: isAuthenticated,
  },
  Fruit: isAuthenticated,
  Customer: isAdmin,
})
```

Also, check [this](https://github.com/maticzav/graphql-shield/issues/232#issuecomment-449711081) comment, I believe these two could be connected 🙂

**Comment by gentleShark** [comment]
based on the example, the authentication is defined on a custom type (which could be the type of a field on another customer type) but most fields use standard graphQL types (String, Boolean, Int, etc). Can regular fields (example, phoneNumber: String) be protected if they are not abstracted into unique types (ex, Fruit and Customer)?
