### ISSUE TITLE
how does "not" work? 

### ISSUE THREAD

**Issue by saimanish1** [maticzav/graphql-shield#242]
# Question about GraphQL concepts

Why I want to use "not"?
My project has only 2 public resolvers. My goal is to make every resolver protected except  login and register. I thought of using "not" for this. Am i missing anything?

**Comment by maticzav** [comment]
Hey @saimanish1 👋,

That is an interesting question! `not` is meant to work as a logic rule - negation. Let's say you want to make sure certain `Book` exists in a database when accessing it, however, should not exist when creating a new one. You could use `not` to keep your code DRY and reuse one rule across two fields.

Furthermore, to have every field protected and only `login` and `register` unprotected, you could set `fallbackRule` to `deny` which will prevent access by default, and set `login` and `register` to `allow`. You could even use the custom rule as a `fallback`. Try something like this;

```ts
import { shield, rule, allow } from 'graphql-shield'

const isUserAuthenticated = rule({ cache: 'contextual' })(
  async (parent, args, ctx) => {
    return ctx.user !== undefined
  },
)

const permissions = shield(
  {
    Mutation: {
      login: allow,
      register: allow,
    },
  },
  {
    fallbackRule: isUserAuthenticated,
  },
)
```

I hope this helps you solve your problem 🙂
