### ISSUE TITLE
The point

### ISSUE THREAD

**Issue by steida** [maticzav/graphql-shield#245]
Why this is better than context helpers?

```ts
setUserTheme: (_, _args, ctx) => {
  ctx.permissions.isAuthenticated();
},
```

Maybe I am missing something, but, why?

**Comment by maticzav** [comment]
@steida I am not sure I understand your question, however, let me try to respond.

GraphQL Shield is an abstraction which allows you to define rules elsewhere - not in your resolvers. Besides that, it also features caching and other optimisation techniques which the majority of people wouldn't implement themselves. I encourage you to read the documentation in the front page and see for yourself what you could benefit from and what not.

To conclude, I wouldn't say GraphQL Shield is a better option or a better design decision. I have talked about this quite extensively in some of the previous issues.  What I do believe, however, is that GraphQL Shield provides a robust toolkit which is easy to use and understand. In the end, it boils down to personal preferences; I, for example, like separation of permission and business logic, while you might prefer something else.

I hope this helps you understand the idea behind `graphql-shield` :slightly_smiling_face:

**Comment by steida** [comment]
Thank you for the answer. I have tried graphql-shield and now I am pretty sure it unnecessary abstraction for me.

**Comment by steida** [comment]
OK, I got it. Thank you.
