### ISSUE TITLE
GraphQL shield to block connect or create from parent mutation

### ISSUE THREAD

**Issue by madhavpandey33** [maticzav/graphql-shield#262]
I working on a scenario wherein I need to block the creation of sub entity from parent mutation and should only allow connect operation. Consider the below schema: 
```
type Person {
    id: ID! @unique
    name: String
    cars: [Car!]!
}

type Car {
   id: ID! @unique
   make: String
   model: String
   year: String
}

```
So for the above schema, I would only like to expose connect operation for car not the create. Like this:
```
mutation CreatePerson {
  createPerson(
    data: { name: "Test Person", cars: { connect: { id: "CAR_ID" } } }
  ) {
    id
    name
  }
}
```

I tried doing it in shield but it keeps giving me error. Any work around would appreciated. Thanks!

**Comment by colinmcd94** [comment]
@madhavpandey33 what did you try? can you include the code of your graphql-shield rule and the text of the error?

**Comment by maticzav** [comment]
#113
