### ISSUE TITLE
FallbackRule being called even though path is set to `allow`

### ISSUE THREAD

**Issue by ChristianJacobsen** [maticzav/graphql-shield#302]
# Question about GraphQL Shield

I'm experimenting with default fallback rule and manually opening other queries with `allow`.
I believe I have set it up correctly, but when I call the 'whitelisted' queries, the fallback rule is being applied. This only happens the first time it's run as the cookie is present the second time and the query successfully runs.

The structure of the app goes like this:
```
express
  cookieParser
    authorizationMiddleware // sets `userId` on the request object
      apollo-server
        graphql-shield // has only one rule, the fallback, being isAuthenticated (checks if `userId !== null`)
          rest of schema
```

My graphql-shield config looks like this:

```javascript
const permissions = shield(
	{
		Mutation: {
			login: allow,
			signup: allow
		}
	},
	{
		fallbackRule: isAuthenticated
	}
);
```

I personally believe that this should work, at least according to my understanding of the docs.
I've used graphql-shield before, but this is the first time I'm changing the `fallbackRule`.

I'm attaching a link to a repo with the exact code [here](https://github.com/ChristianJacobsen/graphql-nexus-test).

Steps to reproduce:
1. `yarn install`
2. `docker-compose up -d`
3. `prisma deploy`
4. Create a `.env` with an `APP_SECRET` field or rename `.env.example`.
5. `yarn start`
6. Open `http://localhost:4001/` and create a user through the signup mutation (this will trigger the fallback)
```graphql
mutation SIGNUP {
  signup(data: {
    email: "test@email.com"
    password: "bananas"
    name: "Monkey Business"
  }) {
    id
  }
}
```
7. Delete the cookie from your browser
8. Attempt to log back in using the login mutation (this will trigger the fallback the first time it's run)
```graphql
mutation LOGIN {
  login(data: {
    email: "test@email.com"
    password: "bananas"
  }) {
    id
  }
}
```
9. Attempt to rerun the login mutation and it will now not throw an error

How do you believe I should best go about debugging/solving this?
I've tried to run both apollo and graphql-shield with debug enabled, but the output is of little help.

Hope this is enough to give a basic concept of what I'm working with.
I thank you all in advance for the help! :smile:

* [X] I have checked other questions and found none that matches mine.

**Comment by maticzav** [comment]
Hey 👋, Could you check the comment I made [here](https://github.com/maticzav/graphql-shield/issues/297#issuecomment-464454891)? I believe your problem stems from `User` type which is not whitelisted. You might be able to see that in the error path as well.

Besides that, I saw you implemented permissions with GraphQL Nexus. Would you be up for including your example in the examples section? 🙂 

I hope this solves your problem.

**Comment by ChristianJacobsen** [comment]
Fudge... I forgot to whitelist those, didn't I? 🙈

Yeah, let me clean it up a little and then I'll send you a PR!

**Comment by ChristianJacobsen** [comment]
#303 :heart:
