### ISSUE TITLE
Way to override the logger ?

### ISSUE THREAD

**Issue by appsolutegeek** [maticzav/graphql-shield#31]
Hi,

Does anyone know if there is a way to override the standard behaviour of throwing the PermissionError or at least some point to intercept it ?

I am using Log4js to do my logging so I would prefer to intercept these errors.

Anyone have any ideas ?

**Comment by maticzav** [comment]
Hey @appsolutegeek 👋,

The new version of `graphql-shield` is to be released very soon. If you could describe your situation in a bit more detail, I can add extra features to meet your needs.

**Comment by appsolutegeek** [comment]
Hi @maticzav ,

Thanks for the reply. Sure, if I can explain it a little better.

So, basically, I am using Log4js to output my logs to the console (as well as file appenders).

I notice in the code, that a normal console.log (wrapped with chalk) is being used. It would be great to be able to overridde this feature. Maybe have some kind of LogImplementation being passed so I can take care of writing the error to the console etc - in my case I would use log4js.

Here is the code I saw from the source

                        console.log(chalk_1.default.blue('DEBUG LOG:'));
                        console.log(err_1);
                        console.log(chalk_1.default.blue('~~~~~~~~~~'));

I currently do this but I don't have access to overrride the graphql-shield logging implementation.

                        this.logger.error('An error has occured', err);

Does this help, it would be really nice to have something like this.

P.s. I have also another suggestion with regards to when an error is thrown inside a resolver, right now its being picked up by graphql-shield and being re-thrown as a PermissionError. 

I have commented here, https://github.com/maticzav/graphql-shield/issues/24   but I will try and give more context.

Thanks again!

**Comment by ravangen** [comment]
To echo @appsolutegeek, I also use a package to help with logging concerns ([winston](https://github.com/winstonjs/winston)). It would be awesome if graphql-shield had some mechanism to control what is output or define a custom logging function. I would rather not have to have conditional logic in Apollo Server's [`formatError`](https://www.apollographql.com/docs/apollo-server/setup.html#graphqlOptions.formatError).

**Comment by maticzav** [comment]
@ravangen @appsolutegeek the next version of Shield will adopt the `graphql-middleware` approach. Would approach, similar to this one http://github.com/maticzav/graphql-middleware-sentry/, work for you? 

If so, we could omit the logger functionality in Shield thoroughly. What do you think?

**Comment by appsolutegeek** [comment]
Yep, that would work for me, that way I can take care of the logging and implement my own.

**Comment by maticzav** [comment]
Great! Thanks for the quick reply. I will close the issue as it seems to be resolved with use of `graphql-middleware`.

**Comment by appsolutegeek** [comment]
Yep great!
