### ISSUE TITLE
Add rule in run time

### ISSUE THREAD

**Issue by israelglar** [maticzav/graphql-shield#319]
# Question about GraphQL Shield

I'm interested in knowing if it's possible to add/remove rule in run-time.

The use case is:

 - I have a list of 'system-rules' and a list of 'user-rules'
 - The 'system-rules' are added when the server starts
 - The 'user-rules' are added if the user use a method `addRule` where he specifies a resolver (eg: query.addUser, mutation.removeUser) and chooses one rule (eg: isAdmin, isAuthenticated)

I have no problem adding the 'system-rules' when the server starts. But I can't find a way to add 'user-rules'.

Is there a way to add rules after the shield middleware is created or to add a new shield middleware in run time?

Thanks!

* [x] I have checked other questions and found none that matches mine.

**Comment by P4sca1** [comment]
I don't think there is an api for that, but maybe this could work:

```ts
import { applyMiddleware } from 'graphql-middleware'

// Your other code.

apolloServer.schema = applyMiddleware(schema, yourNewPermissions)
```

This will recreate and reassign the whole schema to the running apollo server instance.
It should work with `apollo-server` and `graphql-yoga` (as it uses `apollo-server` unter the hood).

**Comment by maticzav** [comment]
@israelglar is this issue still relevant?
