### ISSUE TITLE
InputRule with input argument not working

### ISSUE THREAD

**Issue by aqwert** [maticzav/graphql-shield#325]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

I wanted to get the yup validation working. However it returns `Not Authorised!` when I invoke it. The schema is generated by prisma-nexus for the CRUD operations and contains a data field rather than the actual properties being validated upon

## To Reproduce

1. This is my Mutation (generated by prisma-nexus)

```graphql
type Mutation {
    createUser(data: UserCreateInput!): User!
}
type User {
    id: ID!
    name: String!
}
type UserCreateInput {
    name: String!
}
```

2. This is the invoked query

```graphql
mutation {
   createUser(data: {
     name: "bob"
   }) {id}
}
```

3. I use these permissions

```ts
const isNameValid = inputRule(yup =>
  yup.object({
    data: {
       name: yup.string().required()
    }
  })
);

export const permissions = shield({
  Mutation: {
    createUser: isNameValid
  }
});

```

4. This is the error I see

```json
{
  "data": null,
  "errors": [
    {
      "message": "Not Authorised!",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createUser"
      ]
    }
  ]
}
```

## Expected behavior

The validation should succeed when rules are valid, and reject when not.

## Actual behaviour

The error is returned

## Additional context

Since this is generated, it contains an Input field rather than all the examples I have seen having the validation on the scalar properties themselves on the mutation. Might be related?

**Comment by P4sca1** [comment]
I am not very experienced with `yup`, but I think your schema is invalid.

Try this:
```ts
const isNameValid = inputRule(yup =>
  yup.object({
    data: yup.object({
       name: yup.string().required()
    })
  })
);
```

My guess is that the schema is invalid, which causes an error to be thrown.
Because `graphql-shield` hides errors thrown in rules (unless they are explicitly returned), you only see the fallback error.

**Comment by aqwert** [comment]
Thanks @P4sca1 That worked
