### ISSUE TITLE
Nexus Prisma conflict : Query was defined in resolvers, but it's not an object

### ISSUE THREAD

**Issue by abdullah-almesbahi** [maticzav/graphql-shield#337]
## Describe the bug
I am using this example [this](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-auth)

After hours of spending to find out what is the issue , I figured out is from  graphql-shield

when ever I run "yarn start" , I get this error 
"Query was defined in resolvers, but it's not an object"

if I remove permission file , every thing work fine

## To Reproduce
clone the example and run it,

**Comment by maticzav** [comment]
Hey,
Did you manage to find a solution on your own?

**Comment by sapkra** [comment]
@maticzav I also got this error the reason was upgrading graphql to `14.3.0`.

**Comment by NeroBlackstone** [comment]
@sapkra Thanks for your help! The problem is that graphql dependency version 14.3.0. I rollback to 14.2.1 and resolve that.
