### ISSUE TITLE
Updating typescript types to get improved security

### ISSUE THREAD

**Issue by ScreamZ** [maticzav/graphql-shield#352]
# Feature request

Hello there, thanks for this great tool !

I'm currently using https://graphql-code-generator.com/ which gives me the opportunity to generate the following types directly from my schema.

For clarity, I won't show `Mutation` but they are also generated.

```ts
export type Query = {
  me: User;
  
  searchCourseSessions: Array<CourseSession>;
 
  getCourseSession?: Maybe<CourseSession>;

  getCoachCourses?: Maybe<Array<Course>>;
 
  getPlaces?: Maybe<Array<Place>>;
};
```

Now I would like to type my schema definition to get the following and be sure at compilation time that I'm not missing any security rules related to my scheme (I'm not sure if `graphql-shield` allows to forget one query/mutation ? In case I added a `Partial` keyword).

Here is a what I try to achieve, working with a bit of typescript because I don't want resolvers but rules.

```ts
import { IRules, not, shield } from "graphql-shield";
import { Mutation, Query } from "../../../generated/typings";
import { isAuthenticated } from "./rules";

interface PermissionsSchema {
  Query: Record<keyof Query, IRules>;
  // OR Query: Partial<Record<keyof Query>>, IRules>;
  Mutation: Record<keyof Mutation, IRules>;
}

const schema: PermissionsSchema = {
  Query: {
    me: not(isAuthenticated),
  },
};

// my workaround @ts-ignore
export default shield(schema);
```

The thing is that `shield` function is waiting for a `IRules` type as first argument and my custom type is not matching.
Currently, I'm just doing a // @ts-ignore over the declaration which result to ignoring the following line, but I guess we could find some better way like being able to pass some genericity to the shield function ?

Do you have any idea ? I wanted to used interface extends, but it crushed…

```ts
interface PermissionsSchema extends IRules {
  Query: Record<keyof Query, IRules>;
  // OR Query: Partial<Record<keyof Query>>, IRules>;
  Mutation: Record<keyof Mutation, IRules>;
}
```
`An interface can only extend an object type or intersection of object types with statically known members.ts(2312)`

Thanks you,
Best regards

Andréas

**Comment by maticzav** [comment]
Really cool idea. A fan of it myself as well. Will continue the thread in #466 for clarity.

**Comment by A-Shleifman** [comment]
This should work:

```ts 
type PermissionsSchema = IRules & {
  Query: Partial<Record<keyof Query | '*', IRules>>;
  Mutation: Partial<Record<keyof Mutation | '*', IRules>>;
};

const permissionsSchema: PermissionsSchema = {
  Query: {
  },
  Mutation: {
  },
};
```

**Comment by nshusr** [comment]
this types using nexus full types
``` ts
import { NexusGenFieldTypes, NexusGenObjectNames } from '@/generated/nexus'

type PermissionsSchema = IRules & {
  [k in NexusGenObjectNames | 'Query' | 'Mutation']?: Partial<Record<keyof NexusGenFieldTypes[k] | '*', IRules>>;
};

let ruleTree: PermissionsSchema = {
  Query: {},
  Mutation: {},
  Object: {}
}
```
