### ISSUE TITLE
v 1.2.6 is broken

### ISSUE THREAD

**Issue by soroushm** [maticzav/graphql-shield#38]
I upgraded v.1.20 to 1.2.6 and my compiler getting error graphql-sheild not found!

**Comment by maticzav** [comment]
Hey @soroushm,

I am not entirely sure why this happened, but 1.2.5 and 1.2.6 should both be 2.0.x. The error has been fixed in 2.0.2 though. 

Sorry for the inconvenience, if you know how to remove versions or anything similar I would be more than happy to fix this!

**Comment by maticzav** [comment]
I will close this now, as it seems to be resolved due to no further response.
