### ISSUE TITLE
CPU / Memory Spike once shield is applied

### ISSUE THREAD

**Issue by ltamrazov** [maticzav/graphql-shield#414]
Hi, we are playing around with shield, and started off by just applying an empty rule set like so:

```
...
middlewares = middlewares || [];
middlewares.push(shield({}));
return applyMiddleware(executableSchema, ...middlewares);
...
```

As soon as we do this, everything *seems to work* but we see our CPU and memory usage jump by 30% - 50%. We've also noticed a huge spike in garbage collection. We tried to enable debug mode for some clue:

`shield({}, { debug: true, allowExternalErrors: true })` but no avail. The spike occurs under a load of about 1K RPM, and we cannot reproduce it in local development or on stage servers with a small load. I'm not entirely sure if this is a bug but any pointers would be really welcome.

Thank you

**Comment by lynxtaa** [comment]
I think it's related https://github.com/maticzav/graphql-shield/issues/416

**Comment by maticzav** [comment]
@ltamrazov, to prevent duplication, I'll continue the thread in #416, as @lynxtaa already suggested.
