### ISSUE TITLE
or rule not working

### ISSUE THREAD

**Issue by mhaagens** [maticzav/graphql-shield#424]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Using an "or" fails to run all rules.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

> (Delete the filler code and replace it with your own)

1. This is my GraphQL Schema. 

```graphql
type Query {
  hello: String
}
```

2. This is the invoked query

```graphql
hello
```

3. I use these permissions

```ts
const permissions = shield({
  Query: {
    hello: or(rules.isSuperAdmin, rules.isCompanyManager),
  }
})
```

4. This is the error I see

```ts
Not Authorised!
```

## Expected behavior

Expected to be granted permission as `isCompanyManager` returns true.

## Additional context

Here are the rule definitions used;
```ts
export const rules = {
  isSuperAdmin: rule(options)(async (_, args, ctx, info) => {
    const res = ctx.req.user.permissions.filter(
      e => e.group === "superAdmin"
    ).length
      ? true
      : false;
    return res;
  }),
  isCompanyManager: rule(options)(async (_, args, ctx, info) => {
    const res = ctx.req.user.permissions.filter(
      e => e.group === "companyManager"
    ).length
      ? true
      : false;
    return res;
  })
};
```

**Comment by mhaagens** [comment]
I actually can't get any rules to work when there's more than one;
```
hello: and(
  rules.isAuthenticated,
  or(
    rules.isSuperAdmin, 
    rules.isCompanyManager
  )
)
```
grants access, but the user in this case is not superAdmin or companyManager.

**Comment by mhaagens** [comment]
Sooo...i wrote `no-cache` instead of `no_cache`, thats why it broke. My bad!

**Comment by seawatts** [comment]
I'm actually getting the same error. Setting cache type doesn't help

**Comment by maticzav** [comment]
Could you try using `debug` and post the result here?

**Comment by enbermudas** [comment]
This is happening to me with the next rule:

```js
const isAdmin = rule({ cache: 'contextual' })(
  async (parent, args, ctx, info) => {
    const role = await Role.findOne({ slug: 'administrator' });
    console.log(ctx.user.roleId === role.id);
    return ctx.user.roleId === role.id;
  }
);
```

Funny thing is, this console log actually display `true`, so the `userCreate` permission should work, right?

```js
const permissions = shield({
  Query: {},
  Mutation: {
    // Auth
    login: not(isAuthenticated),
    register: not(isAuthenticated),

    // User
    userCreate: isAdmin,

    // Thread
    threadCreate: isAuthenticated,

    // Reply
    replyCreate: isAuthenticated
  }
});
```

Well, it doesn't. And it displays the `Not Authorised!` message.

**Comment by maticzav** [comment]
You should try setting `User` to `allow` as well. I am quite confident that the server executes the mutation and only hides the result.

Note that rule itself doesn't "know" anything about the return type - you have to set up permissions for that type as well.
