### ISSUE TITLE
Typechecking for authentication rules

### ISSUE THREAD

**Issue by tianhuil** [maticzav/graphql-shield#448]
# Feature request

## Describe the solution you'd like
Assume that different GraphQL resolvers take different types for `arg` (which are explicitly annotated in typescript), e.g. `createUser` takes different `arg` types from `createPost`.  I would like a typecheck to force the `arg` type of (permission) `Rule` resolvers to match the `arg` type of their corresponding GraphQL resolvers.

For example, `isAdmin`'s arg type should match `createUser`'s arg type, while `isUser`'s arg type should match `createPost`'s arg type in the following example

``` ts
shield({
  Mutation: {
    createUser: isAdmin,
    createPost: isUser,
  }
})
```

## Is your feature request related to a problem? Please describe
Currently, the best I can do is manually set the types of `args` for the resolver `Rule` of each field and hope they match the types in the underlying GraphQL queries and mutations as I refactor code.  This is not very typesafe.

Anticipating one input type in your `Rule` resolvers but being passed another type can easily leads to bugs, including inadvertently exposing sensitive user information.  Leveraging the type system would make the critical permissions layer more secure and allow `shield` to be adopted for more sensitive and critical use cases.

## Describe alternatives you've considered

While we can specify arg types on `shield`, they have to be the same across all functions and cannot be customized per request.

## Additional context

Potentially related to https://github.com/maticzav/graphql-shield/issues/352 but they only want to check that all fields of `Query` and `Mutation` are covered by a `Rule`.  This would require that all fields have the same `args`, which is highly unlikely to be the case.

**Comment by maticzav** [comment]
Wonderful idea. I'll continue the thread in #466 for clarity.
