### ISSUE TITLE
v2.0 works as expected :-) debug: property.

### ISSUE THREAD

**Issue by appsolutegeek** [maticzav/graphql-shield#46]
Hi,

I sort of missed the update and just noticed it now.

I just wanted to say that everything seems to be working as planned! Great update and thanks for your time and effort.

Your implementation of passing {debug: true} works great for me to allow graphql-errors to pick up the error message that I originally threw inside my resolvers / permissions.

Maybe the property name should be allowExternalErrors or something similar as debug seems to shout something to do with debugging. 

But hey, it works!

Thanks once again!

**Comment by maticzav** [comment]
Hey @appsolutegeek 👋 , thanks for such nice feedback. If you have some spare time, I would love to merge a PR, otherwise, I will create one by the end of the week.

**Comment by appsolutegeek** [comment]
Done and added. Let me know if it follows what you had in mind.

**Comment by appsolutegeek** [comment]
Great news. It was merged. Thanks

**Comment by maticzav** [comment]
Thank you for the PR!
