### ISSUE TITLE
Cannot use GraphQLObjectType "Query" from another module or realm

### ISSUE THREAD

**Issue by nealoke** [maticzav/graphql-shield#470]
# Bug report

I'm trying to implement this middleware in my `express` based `graphql` server. However on doing so I receive an error which is only there when applying this middleware.

## Received error
```
Error: Cannot use GraphQLObjectType "Query" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
```

![image](https://user-images.githubusercontent.com/17417414/63038058-a0115700-bec0-11e9-8231-e9465ccf426c.png)

## Code
```js
import path from "path";
import { ApolloServer, makeExecutableSchema } from "apollo-server-express";
import { importSchema } from "graphql-import";
import { applyMiddleware } from "graphql-middleware";

import { shield, allow } from "graphql-shield";

import Mutation from "./resolvers/Mutation";
import Query from "./resolvers/Query";

const schema = makeExecutableSchema({
	typeDefs: importSchema(path.resolve("../src/schema.graphql")),
	resolvers: {
		Mutation,
		Query
	}
});

// No errors when you remove shield from the applyMiddleware call 
const adjustedSchema = applyMiddleware(schema, shield({}, { fallbackRule: allow }));

export default new ApolloServer({
	schema: adjustedSchema, // No errors when you pass schema: schema
	resolverValidationOptions: {
		requireResolversForResolveType: false
	},
	context: ctx => ctx
});

```

## Versions used (all latest at this point in time)
```
"apollo-server-express": "^2.6.9",
"express": "^4.17.1",
"express-graphql": "^0.8.0",
"graphql": "^14.4.2",
"graphql-import": "^0.7.1",
"graphql-middleware": "^4.0.0",
"graphql-shield": "^6.0.4",
"prisma-binding": "^2.3.15"
```

## How did I try to debug already
- [x] Remove `node_modules` folder and run `npm install`
- [x] Search the `package-lock.json` file for other versions specified for `graphql`, not the case

**Comment by nealoke** [comment]
As I am debugging this issue I've noticed that this error only occurs when `hoisting` the dependencies up to the root of the monorepo (using `lernajs`). Going inside the `package` and running `npm install` allows met to run this middleware without issue.

I do not however understand how that is possible, so I leave it to the people maintaining this repo to close this issue should it be considered off-topic.

Looking inside my `package-lock.json` files I see only the same versions, also for the ones not visible in the image (first line in each `package-lock.json`) it says the following:

```
"graphql": {
    "version": "14.4.2",
    "resolved": "https://registry.npmjs.org/graphql/-/graphql-14.4.2.tgz",
    "integrity": "sha512-6uQadiRgnpnSS56hdZUSvFrVcQ6OF9y6wkxJfKquFtHlnl7+KSuWwSJsdwiK1vybm1HgcdbpGkCpvhvsVQ0UZQ==",
    "requires": {
        "iterall": "^1.2.2"
    }
},
```

## Searching `"graphql"` in all packages and the root
![image](https://user-images.githubusercontent.com/17417414/63033063-507a5d80-beb7-11e9-81bd-1d97b881545f.png)

**Comment by maticzav** [comment]
Hey @nealoke 👋,

**Comment by nealoke** [comment]
Yes it kind-off is 😢 , the hoisting allows us to keep the same versions of `node_modules`. Modules like `react` also heavily complain if you have different versions and this keeps managing it sane.

Any help would be heavily appreciated!

**Comment by nealoke** [comment]
Looking further into this I found that when I clone the repo of this project to my computer, installing the dependencies and running `npm ls graphql` it says that it needs to have `graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0` required by the `graphql-subscriptions@0.5.8` package.

![image](https://user-images.githubusercontent.com/17417414/63035479-81f52800-bebb-11e9-9687-04c0cdf23870.png)

**Comment by nealoke** [comment]
@maticzav I cannot for the life of me find the issue and how to solve it... 3 hours of trying to debug this has yielded nothing 😢 

From the error I can see that [here something goes](https://github.com/maticzav/graphql-shield/blob/master/src/generator.ts#L117-L122) wrong (in this package's generator).

**Comment by nealoke** [comment]
I found the issue, and like I thought has nothing to do with this package. It basically was an issue with our setup which uses hoisting to pull all the dependencies to the root.

Inside the `webpack.config.js` I was using `webpack-node-externals` but only for the modules in the package (eg. `packages/api/node_modules`). So because most of the packages are pulled to the root it did not exclude these when building the `server.js` with webpack.

### Before
```js
{
    target: "node",
    externals: [
        nodeExternals({
            whitelist: "webpack/hot/poll?1000"
        })
    ]
    // ... Other config for webpack
}
```

### After
```js
{
    target: "node",
    externals: [
        nodeExternals({
            whitelist: "webpack/hot/poll?1000",
            modulesDir: path.resolve(__dirname, "../../node_modules")
        })
    ]
    // ... Other config for webpack
}
```

**Comment by maticzav** [comment]
@nealoke thank you so much for sharing all the progress, the solution, everything. Thanks!

I am genuinely glad you resolved it! 🙂

**Comment by femdave** [comment]
Cannot use GraphQLObjectType "Audit" from another module or realm.

**Comment by anubhavgupta** [comment]
For me the it was a problem when running tests in jest, adding following `jest.config.js`  fixed it for me:
```
resetModules: false,
```
