### ISSUE TITLE
Possibility to re-use shield rule in resolver

### ISSUE THREAD

**Issue by nealoke** [maticzav/graphql-shield#485]
# Question about GraphQL Shield

Hi, first of all thanks for this great library and project! It saved me a lot of headache and time. 😄 

Now for the question, how can I reuse a rule defined for `graphql-shield` in a resolver? This would make the checking of inputs for `mutations` less repetitive. Below an example of the ideal case for re-useability.

## Resolver
```js
import { isAdmin } from "../../../shield/rules";

const updateUser = async (parent, { data: { userId, ...data } }, context, info) => {
	/* ----------  Validation  ----------*/
	await updateUserSchema.validate(data);

	// You are not an admin, so you can't pass the role
	if (!(await isAdmin()) && data.role) {
		throw new Error("You are not allowed to update the role");
	}

	/* ----------  Process  ----------*/
	return User.update(userId, data);
};

export default updateUser;
```

## `graphql-shield` rule
```js
export const isAdmin = rule()(async (parent, args, { req }) => req.user.role === "ADMIN");
```

## Mutation and input type
```graphql
type Mutation {
	updateUser(data: UpdateUserInput): User!
}

input UpdateUserInput {
	userId: String!
	role: UserRoleEnum
	firstName: String
	lastName: String
	telephoneNumber: String
	email: String
	password: String
	language: LanguageEnum
	notificationLevel: NotificationLevelEnum
}
```

**Comment by maticzav** [comment]
Hi! Thank you for the kind words and patience. Your question must have slipped through my inbox. Although I am trying to understand your question, I cannot find the crux of it. Could you elaborate on how `graphql-shield`'s rules would change with the idea you're proposing?

**Comment by nealoke** [comment]
@maticzav let me try to explain it another way 😄 . Currently you cannot use a `rule` function outside `graphql-shield`. It would be nice if you could also a `rule` function inside the resolver. 

Does this make more sense?

**Comment by maticzav** [comment]
Hmm, yeah it does make more sense. Do you maybe have any concrete usage example? What I am particularly interested in is what would be the benefit of using a rule in a resolver as opposed to merely plugging it into the permission system?

**Comment by nealoke** [comment]
Below you can find an example which is with a very simple rule to illustrate the idea. After using shield a while it might not be that necessary but still useful 👍 

## Without re-usability
```
const InviteUser = async (parent, { data }, { req }) => {
	const { role, companyId } = data;

	// Role
	if (role === "ADMIN" && req.user.role !== "ADMIN") {
		throw new Error("You are not authorized to create a user with role admin");
	}

	if (role === "SALESMAN" && req.user.role !== "ADMIN") {
		throw new Error("You are not authorized to create a user with role salesman");
	}

	if (role === "SUBSCRIBER" && (req.user.role !== "SUBSCRIBER" && req.user.role !== "ADMIN")) {
		throw new Error("You are not authorized to create a user with role subscriber");
	}

	// ... other stuff ...
};

export default InviteUser;
```

## With re-usability
```
// Example of shield rule
export const isAdmin = rule()(async (parent, args, { req }) => req.user.role === "ADMIN");

// Resolver
const InviteUser = async (parent, { data }, { req }) => {
	const { role, companyId } = data;

	// Role
	if (role === "ADMIN" && isAdmin(parent, { data }, { req })) {
		throw new Error("You are not authorized to create a user with role admin");
	}

	if (role === "SALESMAN" && isAdmin(parent, { data }, { req })) {
		throw new Error("You are not authorized to create a user with role salesman");
	}

	if (role === "SUBSCRIBER" && (req.user.role !== "SUBSCRIBER" && isAdmin(parent, { data }, { req }))) {
		throw new Error("You are not authorized to create a user with role subscriber");
	}

	// ... other stuff ...
};

export default InviteUser;
```

**Comment by maticzav** [comment]
This is not stale. Thank you for your patience and your example. I don't think it's worth making rules accessible in the bussiness layer of your application. Since rules can only fail or succeed, you should have sufficient information inside your resolver about the information you are testing (i.e. `isAdmin` in the example).

Differentiating between roles in resolvers seems like a bussiness logic that would be very hard to solve with `graphql-shield`. I want to keep `shield` serparted from business logic. I hope you understand. 🙂

**Comment by nealoke** [comment]
Actually it makes sense as you describe it, the app I use this (awesome) library for also is fine without it 👍
