### ISSUE TITLE
how to get passport's Auth info in this middleware

### ISSUE THREAD

**Issue by geminiyellow** [maticzav/graphql-shield#49]
ref: https://github.com/prismagraphql/graphql-middleware/issues/8#issuecomment-392764010

>
> hi all, i use express + passport-oauth2 in my web.
and i want to use graphql to wrap exist restapi, with permission check.
> 
> i follow the examples/permissions , but in this line
> 
> https://github.com/prismagraphql/graphql-middleware/blob/6889d229181e49b4e8711d22a960900b103c2632/examples/permissions/index.js#L40
> 
> the `context.request.isAuthenticated()` alway false, 
> and i debug into the code, it looks like the `this` have nothing about auth info.
> 
> anybody can tell me how to use this library whit passport ?

**Comment by geminiyellow** [comment]
and thanks @maticzav

> Hey @geminiyellow 👋 Could you reopen this issue in https://github.com/maticzav/graphql-shield ?
>
> I think thsi might be well solved there!

**Comment by maticzav** [comment]
Thank you for reopening this issue here. I assume you are using `Yoga` as a server bundler (if not, you should definitely check it out http://github.com/graphcool/graphql-yoga). To pass props from express middleware into `graphql` resolvers, you have to forward your request to the context (afaik, this also defaults if you haven't overwritten it)

```tsx
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req
  }),
})

const isAuthenticated = rule()(async (parent, args, ctx, info) => {
  return ctx.request.isAuthenticated()
})
```

I hope this helps you, otherwise, please provide more details about your application so I can reproduce the bug. 🙂

**Comment by geminiyellow** [comment]
@maticzav thanks for your help.and I did something as yours. and I try to check it in context and check it in rule, alway false. I don’t know why.

**Comment by maticzav** [comment]
@geminiyellow, could you verify that the functions runs correctly if used solely as an express middleware?

**Comment by geminiyellow** [comment]
@maticzav i try to post query from the playground, Is this the reason?
it looks like that yoga is very hard to use with express together,
when add a static folder, the playground cannot access.

**Comment by maticzav** [comment]
Yes, this is probablly it! Try making  a request from a website or copy HTTP headers that should be sent to Playground.

**Comment by geminiyellow** [comment]
oohh, that is it. thank you for your help @maticzav . playground should give a README.

**Comment by maticzav** [comment]
Ayy 🎉 Happy to hear it works! 

I suggest you make a proposal there!
