### ISSUE TITLE
ABAC + graphql-shield

### ISSUE THREAD

**Issue by akaNightmare** [maticzav/graphql-shield#512]
# Question about GraphQL Shield
I am searching for the good/best way how to implement ABAC in graphql-shield. Let's say I have
```
type Query {
  userById(id: ID!): User
  users(filter: UserFilter!): [User!]!
}
```
and have ACL permissions like
`user:view`, `user:list`, no roles/admins/regular/users and etc. Need to write rules for that and as I understand I have to create rules like `canViewUser`, `canListUsers`. What if I have hundreds of queries, mutations, in this case, it will be hard to support the schema and create
for each query separate rule.

* [x] I have checked other questions and found none that matches mine.

**Comment by maticzav** [comment]
Hi @akaNightmare 👋,

That's an interesting question! Have you, by chance, seen the logic rules? The idea behind logic rules is what you've just described; they allow you to compose small, fundamental rules into more complex query-specific permission.

Let me know if I understood your question right. :slightly_smiling_face:
