### ISSUE TITLE
with apollo-server-lambda? 

### ISSUE THREAD

**Issue by mikaelwecode** [maticzav/graphql-shield#53]
Hello! 

is graph-shield possible to use with apollo-server-lambda? 

I tried to found examples on google how to implement with apollo-server-lambda, but no luck :( 

is it possible?

**Comment by maticzav** [comment]
Hey @mikaelwecode, yea I think it should. I just checked out the example on their site, and it seems like you can import schema, therefore you should be able to! Short snippet:

```ts
// graphql.js
const { applyMiddleware } = require('graphql-middleware')
const { shield, ...andeverything } = require('graphql-shield')

const server = require('apollo-server-lambda')
const  myGraphQLSchema = require('./schema');

const permissions = shield({...rules})

const  myGraphQLSchemaWithPermissions = applyMiddleware(myGraphQLSchema, permissions);

exports.graphqlHandler = server.graphqlLambda({ schema: myGraphQLSchemaWithPermissions });
exports.graphiqlHandler = server.graphiqlLambda({
  endpointURL: '/Prod/graphql',
});
```

Also, link to GraphQL Middleware, you'll need that too! http://github.com/graphcool/graphql-middleware.

Ping me if anything seems strange! 🙂

**Comment by mikaelwecode** [comment]
Yes! Thank you, works perfect!  😃

**Comment by maticzav** [comment]
@mikaelwecode happy to hear that!

I think it would be really cool if you could make a PR with your example in case you find some spare time. 😄
