### ISSUE TITLE
not rule works incorrect

### ISSUE THREAD

**Issue by oceandrama** [maticzav/graphql-shield#534]
# Bug report

* [ x ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

`Not` rule doesn't revert rule if it returns Error or string. There is the folowing code in `src/rules.ts`
```
if (res instanceof Error) {
    return res;
} else if (res !== true) {
    return true;
} else {
    return false;
}
````

## Expected behavior

If you return an Error from rule, `not` rule should revert it and return `true`

## Actual behaviour

`Not` rule returns Error as is

## Additional context

This error appears after this PR https://github.com/maticzav/graphql-shield/pull/502, which closes this issue https://github.com/maticzav/graphql-shield/issues/484
I think, you misunderstood the problem. If rule returns `true`, and `not` rule revert it, it throw standard error "You are not authorized", so you cannot describe custom error, if `not` rule did its work

**Comment by maticzav** [comment]
Thanks, fixed.

**Comment by oceandrama** [comment]
Thank you!
