### ISSUE TITLE
Field type permissions

### ISSUE THREAD

**Issue by flyhigh-hifi** [maticzav/graphql-shield#54]
Hi! I have tested permissions applied to type which is returned from query and it seems not to work when resolvers for type were not explicitly defined:
for e.g. this works when I do query **me**:

```
const resolvers = {
  Query: {
    me: (_, args, ctx) => ctx.user;
  },
  User: {
    name(parent, args, ctx) { return parent.name; }
  }
}

const permissions = shield({
  User: {
    name: allow
  }
})
```

and this doesn't, although it has allow rule:

```
const resolvers = {
  Query: {
    me: (_, args, ctx) => ctx.user;
  }
}

const permissions = shield({
  User: {
    name: allow
  }
})
```

Always getting **Not Authorised!** error.

**Comment by maticzav** [comment]
@flyhigh-hifi thanks for reporting this. Could you check out error logs using ` { debug: true } ` option?

Besides that, what's your version of `graphql-shield` and `graphql-middleware`/`graphql-yoga`?

**Comment by flyhigh-hifi** [comment]
Versions:
shield: 2.1.0
yoga: 1.9.2

With debug as true:
```
TypeError: resolver is not a function
    at /Users/mark/Desktop/test/node_modules/graphql-yoga/node_modules/graphql-middleware/src/index.ts:46:9
    at /Users/mark/Desktop/test/node_modules/graphql-shield/src/index.ts:232:16
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mark/Desktop/test/node_modules/graphql-shield/dist/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by maticzav** [comment]
Try upgrading `graphql-yoga` to the latest version. 

The issue about type resolvers has been resolved in one of the latest versions of `graphql-middleware` which should have, as well, been updated in Yoga.

Tell me if that worked out for you! 🙂

**Comment by flyhigh-hifi** [comment]
Bunch of thanks to you, it did!

**Comment by maticzav** [comment]
No problem, I am glad it worked 😄
