### ISSUE TITLE
Consider allowing permissions to be set on a per-field basis

### ISSUE THREAD

**Issue by artemzakharov** [maticzav/graphql-shield#55]
Although I'm an avid user of GraphQL Shield - thank you for creating such a simple means of implementing permissions! - something that has always irked me is that when you implement permissions on a by-type basis, you effectively lose the _relational_ power of GraphQL. Perhaps I'm wrong on this, but this is the issue I see, illustrated with an example:

1. Developer of a social & eCommerce website implements a query to allow fetching user details for a user profile page , something like this:

```graphql
{
  user (input: UserWhereUniqueInput) {
    name
    age
  }
}
```

2. Developer sets a basic `isAuthenticated` permission on the query to ensure that only logged in users can run this query, but adds no permissions beyond that

3. A malicious user pokes around the publicly available schema, and finds out that the website stores payment information as `CreditCard` nodes that have one-to-one relations with `User` nodes 

4. Malicious user simply edits the query to the following, and can now steal people's credit cards:

```graphql
{
  user (input: UserWhereUniqueInput) {
    name
    age
    creditCard {
      number
      securityCode
    }
  }
}
```

I see two solutions to this:

1. Forcibly set the `info` of the query to return a pre-determined result
2. Create a permissions system that parses `info`, compares it to one of several templates based on the user's permissions level, and either throws an error or lets the query through

Since the first solution effectively turns GraphQL into a regular REST endpoint, thereby defeating the purpose, I ended up rolling my own solution that implements #2 using `graphql-fields`. It even allows for functions to be passed in that can evaluate the input at runtime, and determine whether to authorize the operation or not based on the actual query input. Here's an example with a mutation:

```js
export default {
  Mutation: {
    createCollectionAsPartner: rule()(
      async (parent, { collectionCreateInput }, ctx: Context, info) => {

        const permissionFunction: PermissionFunction = (): boolean => {
          return collectionCreateInput.collectionVersions.create.deleted !== false;
        };

        const permissionDefinition: PermissionDefinition = {
          collectionVersions: {
            create: {
              name: true,
              deleted: permissionFunction,
              externalFiles: {
                create: {
                  applicationType: true,
                },
              },
            },
          },
        };

        const verified = verifyMutationPermissions(
          collectionCreateInput,
          permissionDefinition,
          'createCollectionAsPartner'
        );

        return verified;
      }
    ),
  },
};

```

Using this definition, this mutation would work, because `name` is defined as `true` in the `PermissionDefinition` object:

```graphql
mutation {
  createCollectionAsPartner(collectionCreateInput: {collectionVersions: {create: { name: "12345"}}})
}
```

While this one would not, because `approvedManually` is not defined in the `PermissionDefinition` object:
```graphql
mutation {
  createCollectionAsPartner(collectionCreateInput: {collectionVersions: {create: { approvedManually:true}}})
}
```

This example is based on typings generated by Prisma, and limits what kind of input can be passed in when creating this type to the ones defined and equal to `true` in the PermissionDefinition object. If a field is not defined in the object, or is defined but as either `false` or a sync/async function that resolves to `false` at runtime, the operation is denied. The end result is extremely granular control over what is and isn't allowed, without sacrificing the ability to query/mutate by relations, the greatest strength in GraphQL.

Although I wouldn't necessarily expect this to make it into the native library, I'd love to hear everyone's thoughts on this approach! I was surprised to see how little attention this critical security issue is getting within the GraphQL community, but it's possible that I'm just doing something totally wrong and this isn't a problem with a correct setup.

**Comment by maticzav** [comment]
Hey @artemzakharov 👋!

First, thank you for such a warm feedback. It's one of the things that drive me when making open source. 

I think your question is very relevant. Therefore I think we should consider posting it in Prisma Forum as well!

It would be beneficial if you could provide your schema as well, as we can better understand your issue with such context. 

Could you provide that? 🙂

**Comment by artemzakharov** [comment]
Hi @maticzav, 

Unfortunately I can't provide my full schema since it's (ironically) a proprietary project that will have to deal with issues just like the one above, and I don't want to compromise security, but I would be happy to post snippets to clarify any questions about why I took the approach that I did.

I also can't exactly post the full schema even if I wanted to, because I don't _have_ one per se... it's broken down by query/mutation and individual files, and assembled at runtime for a more modular development experience 🙂

My organizational structure looks like this:
![image](https://user-images.githubusercontent.com/25446299/40944035-1f8fd1a2-6808-11e8-80da-9ace00fcd225.png)
And the GraphQL schema for this particular mutation looks like this:

```
type Mutation {
  createCollectionAsPartner(
    collectionCreateInput: CollectionCreateInput!
  ): Boolean
}
```

I wouldn't mind crossposting this to the official Prisma forum, but I'm not sure if I would have the time to oversee it. I'll consider doing it later this week, I just wanted to post it here first since it's a more thematic place to do so, but I'm glad (or not? 😅 ) to hear that this is in fact a real issue.

**Comment by maticzav** [comment]
@artemzakharov I see! I am currently on a short vacation and will be posting an in detail answer to your question in a couple of days. 

Hope it's not urgent! 🙂

**Comment by artemzakharov** [comment]
Thanks for the highly detailed answer, @maticzav! 

I wanted to clarify a couple of things:
1. My model doesn't actually look like that, that was more of an example 😄 
2. I'm not actually modifying the `info` object in any way - I'm only interpreting it to see what information is being requested, and then comparing to a predefined list of allowed fields

Looking at your approach, however, it almost seems like an inversion of my way; instead of defining a template for a query - something like, in written form,  "If you are running a User query, and are an Admin, you can access fields x, y, and z" - you instead say "if your query is asking for field x, you must satisfy criteria a, b, and c". It's a very interesting comparison, and I'm not sure which is better, or more applicable in more situations. I think mine is definitely simpler to implement, but I can see some future issues with scaling if the number of queries and mutations grows substantially while the number of types remains relatively fixed.

Definitely something to think about some more 😄

**Comment by colinmcd94** [comment]
@maticzav Thanks for the great explanation. I was with you right up until "relations are in a way still lost due to this approach". I'm not sure I understand how/why this is the case. 

If I'm using Prisma and on my "application server" I implement resolvers for every field of every schema type (most of which just forward to the Prisma Docker container), relations remain intact, no? 

Or are you just saying that a permissions scheme that blocks access to `creditCard` essentially breaks the client-server contract defined by your schema?

**Comment by maticzav** [comment]
Hey @colinmcd94, 👋  

Sorry for the confusion. What I had in mind with "losing relations" is that there's no "direct" connection between values. Every field gets resolved on its own in a way.

A follow up to your second point; GraphQL always finds a way to stay true to your schema. Therefore, I wouldn't say permission could break the contract. It just changes the result.

Is that what you had in mind? 🙂

**Comment by nolandg** [comment]
@maticzav Been reading a bunch of issues lately, thanks for your awesome clarity! you're good at explaining graphql.

**Comment by TheMikeyRoss** [comment]
is there any way I can have the resolver query to be executed but excludes the fields with `deny` rule?

so for example in my `invoices` query im getting the invoices but based on the user role I'm limiting the `total` field from being viewed by non-admins. and it works by throwing an error on the whole query. Is there a way I can let the query be executed but only exclude the `total` field from it? (or automatically exclude all the fields that have a `deny` rule on them)??
