### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by jdgabriel** [maticzav/graphql-shield#553]
# Explain your question

* [x] I have checked existing issue and found none that could answer my question.

I have the error:

<blockquote>
... \node_modules\graphql-middleware\dist\utils.js:12
    return ((typeof obj.fragment === 'string' || typeof obj.fragments === 'object') &&         
TypeError: Cannot read property 'fragment' of undefined
</blockquote>

#### Resolver
```javascript
const schema = applyMiddleware(
	makeExecutableSchema({
		typeDefs,
		resolvers
	}),
	permissions
);
```

#### Resolver
```javascript
export default {
Query: {
  hello: (_, args, ctx, info) => {
      return {
        id: 1,
        name: 'Gabriel'
        };
      }
    }
};
```

#### Schema
```javascript
type Hello {
  id: ID
  name: String!
}

type Query {
  hello: Hello
}
```

how to solve?

**Comment by maticzav** [comment]
Hi @jdgabriel 👋 ,

Could you verify that you are using the latest version of `graphql-middleware` and `graphql-shield`?

**Comment by jdgabriel** [comment]
thanks for the tip.
I solved my problem by deleting the node_modules folder, it looks like it was some cache uncle.

ty
