### ISSUE TITLE
Rule is not recognised when imported from a package

### ISSUE THREAD

**Issue by dusanmigra** [maticzav/graphql-shield#562]
steps to reproduce:
1. in a package I define and export a shield rule someRule = rule()( someFunc )
2. in main application I import the rule and use it i.e: applyMiddlaware(shield(someRule)) 

But the rule never gets called.
It  works when I move definition of someRule to the main application.

I managed to figure out that the function isRule(x) in utils.js evaluates in the not working case to false (code: x instanceof rules_1.Rule).

**Comment by maticzav** [comment]
If I remember correctly this should have been fixed in one of the recent pull requests.
