### ISSUE TITLE
Possible to do field-level authorization for fields of Nexus-Prisma models?

### ISSUE THREAD

**Issue by jhalborg** [maticzav/graphql-shield#571]
# Question about GraphQL Shield
Hey 👋

I can't tell if it's possible to do field-level read-authorization for a Prisma Nexus generated model/field. For example, if I have the prisma model 

```
type User {
  id: ID!
  firstName: String!
  address: String!
}
```
and I expose that using Nexus-Prisma, how would I go about making custom read rules for the `firstName` and `address` string? If, for example, everyone authorized can read the first name, but  only allow reading the address if you are the user?

Not sure if the question belongs more here or with nexus-prisma, sorry if I came to the wrong place. 

* [x] I have checked other questions and found none that matches mine.

**Comment by maticzav** [comment]
Hey 👋 ,

You'd do it the same way you'd do it in a legacy Apollo Server projects. The idea is that `nexus` returns a schema that you can further restrict using `graphql-nexus`. Besides the schema generation syntax that `nexus` uses, everything should work the same as in the examples.
