### ISSUE TITLE
Is there a way to invalidate the cache for a given rule?

### ISSUE THREAD

**Issue by jderrough** [maticzav/graphql-shield#582]
Let's imagine that a rule fetches information from a database. In most cases, caching would allow not to query the database each time the rule is called. But when the information in the database changes, the cache should be invalidated so that the rule can re-evaluate the information.

Is there a way to invalidate the cache for a given rule and either context or parent/args?

**Comment by maticzav** [comment]
Could this be of any help https://github.com/maticzav/graphql-shield#cache?

**Comment by jderrough** [comment]
Hi @maticzav,

I'm not sure but maybe you can help. Take this example:

```javascript
const isAdmin = rule({ cache: 'contextual' })(
  async (parent, args, ctx, info) => {
    return getUserFromDb(ctx.userId).isAdmin
  },
)
```

Now imagine a scenario where the rule caches the result of `getUserFromDb(ctx.userId).isAdmin` for a user who is an admin based on its ID exposed in the context. But then the user is demoted from its admin role and `isAdmin` is set to false in the database. The cache is then in contradiction with the user's role in the database.

How would you handle the user not being an admin any more and invalidate the rule's cache? Or is the cache immutable? Is `ctx._shield.cache` accessible from outside of the middleware?

**Comment by maticzav** [comment]
@jderrough let me try to grasp the issue by providing some context about how shield works. Shield invalidates cache on each request. Based on your caching settings for a particular rule, however, Shield makes sure that fields protected by the same rule don't execute rule multiple times. That said, there's almost no chance that a user's privileges would change during the scope of one request - the lifetime of a cache.

Perhaps naming is not the best. Still, the idea behind `contextual` is that the rule only needs to invalidate cache once per request (e.g. when determining whether a user is authenticated or not). 

`strict` cache, on the other hand, makes sure that the rule's cache is invalidated based on the parent type passed to the resolver (e.g. when determining whether a particular user can access certain confidential type).

I hope this helps clear the dust. Let me know if that helped you :slightly_smiling_face:.

**Comment by jderrough** [comment]
Oh, I get it now, thanks.
