### ISSUE TITLE
Support function for fallbackError

### ISSUE THREAD

**Issue by nealoke** [maticzav/graphql-shield#601]
# Feature request

## Is your feature request related to a problem? Please describe

Currently you can supply a `fallbackError` which is great but we can't really localize any of the error messages in my case because the language is attached to the context. I think it would make sense to allow a function inside the `fallbackError`.

## Describe the solution you'd like

```
{
	// ... other settings
	fallbackError: (args, ctx, info) => {
		// Perform localization or do custom logic
	}
}
```

**Comment by maticzav** [comment]
@nealoke that does make a lot of sense. Would you be interested in contributing a PR? 🙂

**Comment by nealoke** [comment]
Written on my todo list but probably will take some time until I have a timeslot for this 😉

**Comment by n1ru4l** [comment]
@maticzav Would this also be a viable solution for handling swallowed errors?

E.g. right now a TypeError that is raised by a simple typo could be mapped to the fallbackError (which is done for the outside world), but also bad for the developers as they have no option to log the actual error to Sentry or similar.

Or is there another solution to this?

I am aware of the `allowExternalErrors` option, however, it does not mask the error to the outside world, as you probably don't want to use it inside production.
