### ISSUE TITLE
incorrect(?) error in a nullable list

### ISSUE THREAD

**Issue by helios1138** [maticzav/graphql-shield#607]
# Bug report

## Describe the bug

Given a schema

```gql
type User {
  name: String!
  token: String!
}

type Thread {
  members: [User]!
}
```

And permissions

```ts
User: {
  token: someRule
}
```

When running a query such that it violates the rule

```gql
... on Thread {
  members {
    name
    token
  }
}
```

Instead of permission error, I get an error

```
Cannot return null for non-nullable field User.name.
```

This seems to have something to do with a specific combination of having a list and nullability settings because here are a few examples of what can be changed either in schema or in a query so that I don't get this issue (meaning I get the correct permission error):

- if I request the same fields on a `User` that is not part of a list
  ```gql
  ... on User{
    name
    token
  }
  ```
- if I don't request the `name`
  ```gql
  ... on Thread {
    members {
      token
    }
  }
  ```
- if I make `name` nullable
  ```gql
  type User {
    name: String
    token: String!
  }
  ```
- if I make `User` non-nullable in `members`
  ```gql
  type Thread {
    members: [User!]!
  }
  ```

## Notes

Reproducible on the latest version of `graphql-shield`

**Comment by maticzav** [comment]
Hey 👋,

Thank you for opening the issue. I am genuinely interested in what’s causing this behaviour. Could you perhaps create a small reproduction in CodeSandbox so that I can play around?
