### ISSUE TITLE
Apply rule to input fields

### ISSUE THREAD

**Issue by GabrielFiel** [maticzav/graphql-shield#609]
Hi.
I'm using prisma2 and nexus.

I wanted to prevent the field `role` from `User` to be written or read by non-admin users.
Then I set `role` from `User` Object Type to be allowed only for Admins.

```
export const permissions = shield(
  {
    Mutation: {
      createUser: isAuth,
      ...
    },
    User: {
      role: isAdmin,
    }
  }
)
```
Non-admins can't get `role` field, it works :smiley: 
The problem here is that Object Type `User` is being used only by responses. 
Nexus generates a lot of Input Types for User (`UserWhereInput`, `UserOrderByInput`, `UserUpdateManyMutationInput`, `UserUpdateInput`, `UserCreateInput`) and every Mutation or Query uses a different one as argument.

I tried like below, but it doesn't  work :cry: 

```
User: {
  role: isAdmin,
},
UserWhereInput: {
  role: isAdmin,
},
UserOrderByInput: {
  role: isAdmin,
},
UserUpdateManyMutationInput: {
  role: isAdmin,
},
UserUpdateInput: {
  role: isAdmin,
},
UserCreateInput: {
  role: isAdmin,
}
```
Do you guys know how to achieve this?

**Comment by maticzav** [comment]
Hi @GabrielFiel!

Could you further describe your issue? An example would be beneficial. I cannot get my head around why you'd need to use rules on `InputTypes` the way you are describing above.
