### ISSUE TITLE
Advanced caching rules (e.g. for permissions)

### ISSUE THREAD

**Issue by rajit** [maticzav/graphql-shield#626]
Is there a way with GraphQL Shield to apply more advanced caching strategies to rules? Let's say I have a user who upgrades their account to give themselves increased permissions. At this point I'd want to evict the related items in the cache so that they were recalculated. Of course I'd want to do this across all hosts if my API was running across multiple servers. Do you have a recommended approach for such a scenario?

**Comment by maticzav** [comment]
Hi!

Could this be related https://github.com/maticzav/graphql-shield/issues/582?

**Comment by rajit** [comment]
Thank you, yes that's helpful. In that case I'd like to ask:

Is there anyway to cache across requests? e.g. if an admin user is using the API, and makes 10 requests in 5 seconds, only check their admin status on the first request and then afterwards use the cache.

**Comment by maticzav** [comment]
I don't think there's an elegant and quick way to implement this in `graphql-shield` since it wholly relies on the resolver's context at the moment. I suppose you could do some optimisation inside context (i.e. upon resolving user identity), but that wouldn't be related to `graphql-shield`.

**Comment by rajit** [comment]
Do you have any plans with `graphql-shield` to enhance the caching facilities at all? Just the ability to share a cache across requests, in conjunction with the ability to override the hash function would be very powerful, for instance.

**Comment by rajit** [comment]
Even an inbetween solution of supporting caching across requests with short TTLs, and ideally an LRU implementation, could work very well depending on the use-case.

**Comment by maticzav** [comment]
@rajit would it be possible that you use your own caching function and persist the context there?

**Comment by rajit** [comment]
@maticzav Sorry for not replying sooner.

> would it be possible that you use your own caching function and persist the context there?

I can see that it's possible to override the function that calculates cache keys, but I haven't been able to see how to override caching more broadly. Would you be able to give an example?
