### ISSUE TITLE
Example Implementation with Auth0

### ISSUE THREAD

**Issue by BjoernRave** [maticzav/graphql-shield#628]
I am looking into using Auth0 in my new project and was wondering if there is someone who has already integrated Auth0 with graphql-shield and if it's even a good idea. 

Might be a good idea from auth0 to provide some kind of plugin for an easy integration? @luisrudge @ngonzalvez

**Comment by maticzav** [comment]
Hey 👋 ,

Have you tried using the `ctx` as a source of user identity? I think you could use  existing Auth0 express-compatible middleware to auth user, and use `ctx` to resolve permissions.

**Comment by BjoernRave** [comment]
@maticzav yea, I guess I will just resolve the user in the context creation function and then append that to it. Thought maybe someone has already some experience with it or some tips. I can close it again

**Comment by maticzav** [comment]
Makes sense! Let me know if you find anything. Would love to add it to the examples section.
