### ISSUE TITLE
When using '*': deny it's blocking apollo federation realted fields

### ISSUE THREAD

**Issue by xpolb01** [maticzav/graphql-shield#641]
I'm using graphql-shield with Apollo Federation 

## To Reproduce
```js
const permissions = shield({
  Company: and(isAuthenticated, or(and(isEmployee, userExists), isAdmin)),
  Query: {
    '*': deny, // This will make sure you will add a handler to the rule
    company: and(isAuthenticated, or(and(isEmployee, userExists), isAdmin)),
    clinic: and(isAuthenticated, or(and(isEmployee, userExists), isAdmin)),
    me: and(isAuthenticated, isEmployee),
  },
  Mutation: {
    '*': deny, // This will make sure you will add handler to the rule
    createClinic: and(isAuthenticated, or(and(isEmployee, userExists), isAdmin)),
  }
});
```

In order to make it work I use these permissions:

```ts
const permissions = shield({
  Company: and(isAuthenticated, or(and(isEmployee, userExists), isAdmin)),
  Query: {
    '*': deny, // This will make sure you will add handler to the rule
    _service: allow,
    _entities: allow,
    companies: and(isAuthenticated, isAdmin),
    clinic: and(isAuthenticated, or(and(isEmployee, userExists), isAdmin)),
    me: and(isAuthenticated, isEmployee),
  },
  Mutation: {
    '*': deny, // This will make sure you will add handler to the rule
    createClinic: and(isAuthenticated, or(and(isEmployee, userExists), isAdmin)),
  }
});
```

This is the error I see

When I deploy this and graphql-gateway tries to fetch the data for the service it fails with error:
```js
{
    message: 'Not Authorised!',
    locations: [ [Object] ],
    path: [ '_service' ],
    extensions: { code: 'INTERNAL_SERVER_ERROR', exception: [Object] }
  }
```

## Expected behavior

`'*': deny` should not affect default federation fields

**Comment by eduhenke** [comment]
You are using federation with graphql-shield, could you show us your code, as I'm having a problem with an even simpler permission, as stated in: #456 

Thanks!

**Comment by maticzav** [comment]
@xpolb01 could you check what is the return type of `_service` and whether it is blocked?

**Comment by xpolb01** [comment]
> @xpolb01 could you check what is the return type of `_service` and whether it is blocked?

It's a default `_root` property for a federated schema: https://github.com/apollographql/apollo-server/blob/c149c6f4ab635d368cc7397090798fd42d317bce/docs/source/federation/federation-spec.md

It's being blocked when `graphql-gateway` is trying to create an authenticated data source:

```ts
const gateway = new Apollo.ApolloGateway({
  serviceList: [
    { name: 'service', url: SERVICE_URL },
  ],
  buildService({ name, url }): AuthenticatedDataSource {
    return new AuthenticatedDataSource({ url });
  },
});
```

**Comment by xpolb01** [comment]
> You are using federation with graphql-shield, could you show us your code, as I'm having a problem with an even simpler permission, as stated in: #456
> 
> Thanks!

All I do is this:
```js
const federatedSchema = buildFederatedSchema([patientSchema]);

// Applying permissions onto the schema 
const federatedWithShield = applyMiddleware(
    federatedSchema,
    permissions
);
```

**Comment by maticzav** [comment]
Could you try setting the `_Service` type to `allow`?

**Comment by xpolb01** [comment]
`_service` works. I was trying to raise a point that `'*'` should omit those values

**Comment by maticzav** [comment]
@xpolb01 happy to hear that. However, I don't understand why it should omit those fields. GraphQL Shield is not explicitly built for Apollo Federation. Why do you think that would be beneficial?
