### ISSUE TITLE
Race rule - Break early on successful authorization within "or" rules

### ISSUE THREAD

**Issue by Tybot204** [maticzav/graphql-shield#645]
# Feature request

## Is your feature request related to a problem? Please describe

I think `or` rules should break early if it is found the first method returns true so that the second method never gets called, potentially slowing requests down checking unnecessary permissions.

I am using an `or` rule in some of my permissions to allow admin users to read all instances of a record, while non-admins can only view records that have `visible: true` set in my DB. My permissions look a bit like this:

```ts
import { or, rule, shield } from "graphql-shield";

interface IContext {
  user: {
    permissions: string[]
  }
}

const hasPermission = (permission: string) =>
  rule(permission)((_1, _2, context: IContext) => {
    return context.user.permissions.includes(permission);
  });

const isVisible = (entity: any, argName: string) =>
  rule(`visible:${entity}`)(async (_, args) => {
    const object = await entity.findOne(args[argName]);
    return object.visible
  });

const permissions = shield({
  Query: {
    record: or(
      hasPermission("read:invisible_records"),
      isVisible(Record, "recordId")
    )
  }
})
```

I am using TypeORM, but my problem is generic to any DB lookup. If a user has the `read:invisible_records` permission, I don't want to waste time on a DB request since I already know that user can view the record, regardless of its visible status. Currently, I can see the DB query being run no matter what `hasPermission` returns.

## Describe the solution you'd like

I would expect an `or` permission check that succeeds the first method to not call the second method at all.

## Describe alternatives you've considered

Since I need to look up the record eventually anyways to return what the user requested, I could move my permission check to the resolver itself. This seems like an anti-pattern based on the docs as shield is intended to be used as middleware before my resolvers ever get called.

**Comment by maticzav** [comment]
Implemented in the latest version.
