### ISSUE TITLE
Unknown object type "promise" error when uploading files

### ISSUE THREAD

**Issue by BjoernRave** [maticzav/graphql-shield#688]
Hey, when trying to upload files and validating values uploaded alongside the files I get the following errror: 

`Unknown object type "promise"`

It gets thrown by `object-hash`, which is probably tyring to create a hash for caching.

Because with apollo the uploaded files are a promise it throws an error

**Comment by maticzav** [comment]
I am quite confident this is a duplicate.  The rules accept a custom cache function and setting the cache to `no_cache` should also work.

**Comment by BjoernRave** [comment]
@maticzav sorry, for the duplicate. Setting cache to `no_cache` did indeed fix the problem. Thank you :)
