### ISSUE TITLE
Custom Error is not thrown, instead the fallback error is used

### ISSUE THREAD

**Issue by hammenm** [maticzav/graphql-shield#730]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

For my login Mutation, I would like to throw the error when password do not match. However the error returned is always `Not Authorized`. I tried to set `debug: true`, but instead the intended behavior works when I add this flag...

## To Reproduce

1. This is my GraphQL Schema. 

```graphql
type Mutation {
  login(login: String!, password: String!, rememberMe: Boolean): AuthPayload
}

type AuthPayload {
  token: String
  user: User
}

type User {
  id: ID!
  name: String!
  login: String!
  role: Role!
  archive: Boolean!
}
```

2. This is the invoked query

```graphql
mutation($login: String!, $password: String!, $rememberMe: Boolean) {login(login: $login, password: $password, rememberMe: $rememberMe) {token user { id name role } } }
```

3. I use these permissions

```js
import { shield, allow } from 'graphql-shield';

const isAuthenticated = rule({ cache: 'contextual' })(
  async (parent, args, { db, userId }) =>
    db.exists.User({
      id: userId,
      archive: false,
    })
);

const permissions = shield(
  {
    Mutation: {login: allow},
    AuthPayload: allow,
    User: {
        id: allow,
        name: allow,
        login: allow,
        archive: allow,
        role: allow,
    }
  },
  {
    fallbackRule: isAuthenticated,
  }
);
```

## Expected behavior

- Have my mutation return my own Error
- Adding `debug: true` should not change the behavior of the permission

**Comment by maticzav** [comment]
I am not sure I understand your issue entirely. Perhaps [this](https://github.com/maticzav/graphql-shield#custom-errors) could be of help? 🙂

**Comment by hammenm** [comment]
Below is the code with the expected thrown error :

```js
export async function login(_, args, { db }) {
  const user = await db.query.user(
    { where: { login: args.login } },
    '{ id password name role }'
  );
  return compareHash(args.password, user.password)
    .then(validPassword => {
      if (!validPassword) {
        throw new LoginError();
      }
      return generateTokenFromUser(user, options);
    })
    .then(token => ({ token, user }));
}
```

When `debug: true` the correct error is returned (ie `LoginError`) but when `debug` is not specified, the error returned is the default one `GraphqlError: Not Authorized`.
I would like to have the `LoginError` to be returned

**Comment by hammenm** [comment]
To recap, the code matches what is specified in the doc, but only work when `debug: true` (which won't happen in production)

**Comment by maticzav** [comment]
@hammenm your code throws the error, the docs state that you should `return` the error.

**Comment by hammenm** [comment]
Oh yeah you are right! Thank you for that! 😄 

I have two questions and then we can close this issue if it is good for you:
* Is it normal that `debug: true` changes this behavior?
* Is it specified somewhere in graphql server specification that we should return errors instead of throwing them? Or is it something special for graphql-shield.

Anyway my code works great now! Thank you for your quick intervention

**Comment by maticzav** [comment]
It's GraphQL Shield only case. I am not sure I understand how the behaviour changes. Please read the docs, I am quite certain you'll find the answer to your specific case there. 🙂
