### ISSUE TITLE
Recommended way of combining rules

### ISSUE THREAD

**Issue by Sytten** [maticzav/graphql-shield#733]
# Question about GraphQL Shield
Our schema is split between multiple typeDefs files and we use a lot of type extensions. I would like to keep the permissions near that. Either inside a resolver extension (similar to https://github.com/maticzav/graphql-shield/issues/152, but using https://github.com/Urigo/graphql-tools/issues/1279 and https://github.com/graphql/graphql-js/issues/1527) or as a separate file beside the typeDefs.
My problem is that we need to combine that in some way after it. What is the recommended way to do that?

Thanks!

**Comment by Sytten** [comment]
So the current work around it to use lodash merge, it works good enough for us but it will not detect duplicate rules. Maybe a util in the library would be useful? @maticzav

**Comment by maticzav** [comment]
Thank you for your patience with this question.

My thinking is that if you can already do that with other libraries, we don't need new functions per se. If, however, we figure out that there are potential features that can't be achieved without specific "internal" function, we should create a new one.

**Comment by Sytten** [comment]
Yeah external is fine I guess.
