### ISSUE TITLE
Falling back to to default cache when redis server is down

### ISSUE THREAD

**Issue by CathalAherne** [maticzav/graphql-shield#747]
Hello,
Currently we have a need to handle the situation where when redis server cache is down, we want to switch to the default cache during run time. We are using shield for rate limiting and this is the current implementation:

```
const redis = new Redis("localhost");

    redis.exists("key").then((x) => {
        redisDown = false;
    }).catch(() => {
        redisDown = true;
    });

    return redisDown ? getDefaultRateLimitRule() : getRedisRateLimitRule(redis);
}

function getRedisRateLimitRule(redis: any) {
    // rateLimitTimeWindow = 1;
    return createRateLimitRule({
        formatError: ({ fieldName }) => {
            return `Rate limit exceeded on calls to ${fieldName}`;
        },
        identifyContext: (ctx) => ctx.id,
        store: new RedisStore(redis)
    });
}

function getDefaultRateLimitRule() {
    // rateLimitTimeWindow = 2;
    return createRateLimitRule({
        formatError: ({ fieldName }) => {
            return `Rate limit exceeded on calls to ${fieldName}`;
        },
        identifyContext: (ctx) => ctx.id,
    });
}
```

This works fine and it switches over seamlessly without losing any data. The issue is we need to know how this works, Im having issues debugging this. The code above only gets invoked once. Im wondering where does the switch happen within shield. How would I best debug this? Also is it possible to set a max number of entries for the default cache or dynamically reduce the max query calls after we switch over to the default cache. We need this as there is a concern the default cache will use up all the memory and cause a crash.

Thanks in advance

**Comment by maticzav** [comment]
Hey 👋 ,

Thank you for being so patient with my reply. Does the `cache` section of the docs help you in any way?

https://github.com/maticzav/graphql-shield#cache
