### ISSUE TITLE
"and" relations not conditional

### ISSUE THREAD

**Issue by ianwensink** [maticzav/graphql-shield#823]
# Bug report

## Describe the bug
When using the `and` helper from the library, it seems as if a failing rule is not preventing the others from being executed. The example on this shows the use of the user object from the context, of which the existence (`null`) is checked in the first `isAuthenticated` rule. If this rule resolves to `false`, the `isAdmin` rule is still executed, resulting in an exception since `user` is null, so `user.role` is invalid.

## Expected behavior
I would either expect rules to work like logical AND's (a failing condition will stop the other conditions from being checked), or that the example wouldn't suggest that I can assume `user` is an object whenever the first rule passes.

**Comment by ianwensink** [comment]
Edit: I will investigate whether the problem actually lies within `graphql-shield`, or in [nexus-plugin-shield](https://github.com/lvauvillier/nexus-plugin-shield).

**Comment by maticzav** [comment]
Have you tried using `chain` rule?

**Comment by ianwensink** [comment]
Hi @maticzav. Thanks for your reply. I think this resolves my issues! Gotta say the naming is a bit confusing, since I assumed `and()` already chained it.

Thanks!
