### ISSUE TITLE
Add example of nexus-graphql-shield to README?

### ISSUE THREAD

**Issue by cktang88** [maticzav/graphql-shield#861]
In the README, there's mentions of Yoga and using `graphql-middleware`, but nothing mentioning how to use it with Nexus. Nexus is an actively maintained backend framework that integrates well with Prisma, while Yoga has not been actively maintained for over a year. There is a plugin called `nexus-graphql-shield` that does basic integration with Nexus, perhaps at least a mention or a code snippet could be put in the README to let visitors know that it supports integrating with Nexus?

Nexus plugin: https://github.com/lvauvillier/nexus-plugin-shield
Nexus: https://nexus.js.org/
Yoga deprecation: https://github.com/prisma-labs/graphql-yoga/issues/449

**Comment by cktang88** [comment]
@maticzav Can I make a PR for this?

**Comment by maticzav** [comment]
Yup! I would love to merge a PR.
