### ISSUE TITLE
Is it possible to apply wildcard rules to specific query/mutation fields

### ISSUE THREAD

**Issue by Slmii** [maticzav/graphql-shield#873]
# Question about GraphQL Shield

I've been looking in the docs but could find anything about (I might've missed it) but is it apply the rules specified in a wildcard `*` to a specific `query/mutation` field rule.

For example
```
Mutation: {
        '*': and(isAuthenticated, hasPermission),
        addUser: validateInput, // this would also have the rules applied in the wildcard
 }
```

If I want to achieve the above I need to do
```
Mutation: {
        '*': and(isAuthenticated, hasPermission),
        addUser: and(isAuthenticated, hasPermission, validateInput)
 }
```
I saw something related to this question in #680 but its not been updated for a while.
# Question about GraphQL concepts

Please describe the concept you are interested in. If possible also provide links and source of the problem that you have.

- [x] I have checked other questions and found none that matches mine.

**Comment by maticzav** [comment]
Hey! 👋

Thank you for being so patient. I don't think it's possible since this is a very edge case scenario. It would be difficult to find a balance in the API that would allow it.

**Comment by maticzav** [comment]
Related to #928. I will keep the discussion in that thread.
