### ISSUE TITLE
Use graphql-shield with graphql and express-graphql

### ISSUE THREAD

**Issue by nmquaan** [maticzav/graphql-shield#94]
Hi everyone,
I'm doing a project that uses graphql but I use graphql with express-graphql. But I want to apply graphql-shield to my project.
Please help me! 
Thanks for the support!
`import {
  GraphQLSchema,
  GraphQLObjectType,
} from 'graphql';`
`import { user, users, usersByRole } from './queries/UserQueries';`
`const queryType = new GraphQLObjectType({
  name: 'QueryType',
  description: 'The root for all queries available.',
  fields: {
    users,
    user,
    usersByRole,
}
});`
`// Creating schema`
`const schema = new GraphQLSchema({
  query: queryType,
});`
`export const permission = shield({
  Query: queryType,
});`
`export default schema;
`

**Comment by maticzav** [comment]
Hey @nmquaan 👋 I think this is a duplicate of #53 in a way, tell me if that solved your problem. 😄

**Comment by nmquaan** [comment]
Thanks for the support @maticzav 
I solved my problem.
I will close this issue.
