### ISSUE TITLE
"Not Authorised!" on a field make the containing object null

### ISSUE THREAD

**Issue by AlessandroFerrariFood** [maticzav/graphql-shield#97]
First of all I think that graphql-shield add a clean, generic and maintainable security layer to graphql.
It don't replace ad-hoc fine-grained security check in some resolver for special cases but make easy to add uniform basic access control on all your schema.
So kudos to you!

I'm implementing a field level access policies with graphql-shield but I'm having a strange issue.
When a field is "Not Authorised!" the parent object is set to null.
Here is an example.

Permissions:
`const permissions = shield({
	Query: {
		node: allow,
	},
	User: {
		name: allow,
		secret: deny
	}
});`

Query:
`{
	node (id: 'myId') {
		... on User {
			name,
			secret
		}
	}
}`

Expected result:
`{
	"data": {
		"node": {
			name: "My name"
		}
	},
	"errors": [
		{
			"message": "Not Authorised!",
			"locations": [
				{
					"line": 31,
					"column": 3
				}
			],
			"path": [
				"node",
				"secret"
			]
		}
	]
}`

Actual result:
`{
	"data": {
		"node": null
	},
	"errors": [
		{
			"message": "Not Authorised!",
			"locations": [
				{
					"line": 31,
					"column": 3
				}
			],
			"path": [
				"node",
				"secret"
			]
		}
	]
}`

It's not an errorPolicy issue on the client because this is extracted from the raw http response.
Only parent object is set to null.
A connection query has all fields normally returned but edges are like this
`
edges {
	edge {
		node: null
	},
	edge {
		node: null
	},
	edge {
		node: null
	},
	edge {
		node: null
	}
}
`

I'd like to adopt graphql-shield so let me know if I can help to solve this issue.
Thanks.

**Comment by maticzav** [comment]
Hey @AlessandroFerrariFood 👋 

Could you share the chunk of your schema that is being affected? 🙂

**Comment by AlessandroFerrariFood** [comment]
I have a big proprietary application I can't share but I assembled a strongly reduced but complete version to test the issue on.
Here is its schema
[schema.txt](https://github.com/maticzav/graphql-shield/files/2192621/schema.txt)
Permission are
`const permissions = shield({ User: { firstName: allow, lastName: allow, secret: deny } });`
Following query
`{
  currentUser {
    name
  }
}`
correctly give
`{
  "data": {
    "currentUser": {
      "name": "Paolo Rossi"
    }
  }
}`

Following query
`{
  currentUser {
    name
    secret
  }
}`
wrongly give
`{
  "data": {
    "currentUser": null
  },
  "errors": [
    {
      "message": "Not Authorised!",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "currentUser",
        "secret"
      ]
    }
  ]
}`
but I expected
`{
  "data": {
    "currentUser": {
      "name": "Paolo Rossi"
    }
  },
  "errors": [
    {
      "message": "Not Authorised!",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "currentUser",
        "secret"
      ]
    }
  ]
}`
or similar.

**Comment by AlessandroFerrariFood** [comment]
You are right!
I missed the not-null.
Changing solved it.

Thank you very much!

PS: `node` Query field called with wrong `id` returns a `not found` graphql error

**Comment by mkaradeniz** [comment]
Hey,

I have a related issue to this. Let's say my schema looks like this:

```graphql
type Resource {
  id: ID!
  createdBy: User
}

type User {
  id: ID!
  name: String!
}
```

I now have a field rule on `Resource` to deny unauthenticated users from querying `createdBy`.

When I now query `Resource` unauthenticated like this:

```graphql
{
  resources {
    id
    createdBy {
      id
      name
    }
  }
}
```

I would have expected to get this result:

```json
{
  "data": {
    "resources": [
      {
        "id": 1,
        "createdBy": null
      },
      {
        "id": 2,
        "createdBy": null
      }
    ]
  }
}
```

But I'm actually getting an error:

```json
{
  "error": {
    "errors": [
      {
        "message": "Cannot return null for non-nullable field User.id.",
        "locations": [
          {
            "line": 6,
            "column": 7
          }
        ],
        "path": [
          "resources",
          0,
          "createdBy",
          "id"
        ]
      },
      {
        "message": "Cannot return null for non-nullable field User.id.",
        "locations": [
          {
            "line": 6,
            "column": 7
          }
        ],
        "path": [
          "ressources",
          1,
          "createdBy",
          "id"
        ]
      }
    ],
    "data": {
      "resources": [
        {
          "id": 1,
          "createdBy": null
        },
        {
          "id": 2,
          "createdBy": null
        }
      ]
    }
  }
}
```

Is there a way to suppress this error so it just returns `null` for `createdBy` and be done with it?

**Comment by maticzav** [comment]
Hey, let's see what's going on!

_tldr; I think the "problem" is on the frontend because it defaults to error and doesn't consume the data below_

So, I think there are some settings regarding how client handles errors. What I wanted to ask before is how does the data in the error case relate to your schema (the `rugs` part).

**Comment by mkaradeniz** [comment]
Oh gosh, sorry. I wanted to edit the code I posted so it is more clear, but I forgot to edit the error part. I edited my original post.

The frontend itself isn't built yet, this is all from the playground.

I think it all boils down to this: If someone queries a nullable field without permission to access this field, I simply want to return `null` instead of throwing an error.

**Comment by maticzav** [comment]
> I think it all boils down to this: If someone queries a nullable field without permission to access that field, I simply want to return `null` instead of throwing an error.

It makes sense, no worries! 🙂 

I mean, the easiest way to do that is to make fields nullable, as you mentioned. It's not possible to not throw a permission error, but that shouldn't be a problem, in my opinion.

Why's ignoring the error, and only collecting the data, not an option?

**Comment by mkaradeniz** [comment]
> Why's ignoring the error, and only collecting the data, not an option?

The problem I was facing is, that (using nexus framework) that errors were returning `500` status codes. With this hack https://github.com/graphql-nexus/nexus/issues/761#issuecomment-627989689 I was able to change it. Now it does return an `errors` array but also the `data` so I should be able to ignore it later

So I guess it was more of a `nexus` issue than a `graphql-shield` one, though I would've preferred to not throw an error but I get that this is probably not intended.

Thanks so much :)

**Comment by fforres** [comment]
In case other people are looking for the same, link that @mkaradeniz is not existing any more (Maybe this one was the same?)
https://github.com/graphql-nexus/nexus/issues/383#issuecomment-589380036

For context, what we want to do, is format the response (in this case in apollo) so 
```TS
const server = new ApolloServer({
  // more config
  formatResponse: (response, { operationName }) => {
    if (response && operationName) {
      return {
        ...response,
        data: response.data || {
          [operationName]: null,
        },
      }
    }

    return {
      data: null,
    }
  },
})

```
