### ISSUE TITLE
Mono repo (lerna) MiddlewareError: Type generator exists in middleware but is missing in Schema.

### ISSUE THREAD

**Issue by Bram-Zijp** [maticzav/graphql-shield#970]
I am working with a mono repo using "lerna". I ended up creating my shield rules for two endpoints in one module and import this module as dependency in the endpoint projects. When I imported the the rules initialized with shield from a dependency, I would get this error: `MiddlewareError: Type generator exists in middleware but is missing in Schema.`.

To solve this problem I ended up doing this:

```

export const permissions = (passedShield: typeof shield) =>
  passedShield({
    ...
  });

```

**Comment by maticzav** [comment]
@Bram-Zijp this often occurs due to version mismatch with `graphql-middleware`. I hope you've solved your problem 🙂
