### ISSUE TITLE
Use with apollo-errors?

### ISSUE THREAD

**Issue by nmquaan** [maticzav/graphql-shield#98]
Hi @maticzav,
When I use CustomError of 'graphql-shield" I see it throw message error not clearly, I want to use with apollo-errors. 
This link package: [https://github.com/thebigredgeek/apollo-errors](url)
Please help me use it!
Thanks for the support!

**Comment by appsolutegeek** [comment]
You can do this using allowExternalErrors.

Look into the readme, it allows non interception of errors. This is then left up to another framework

**Comment by maticzav** [comment]
Starting to build the comminity! 🎉🎉

**Comment by nmquaan** [comment]
Thanks for the support!
This issue solved.

I have a difference problem when submit multiple query in a request, query has difference role but when permission fail on a query so difference query still has data.
Expected data: 
`{
  "errors": [
    {
      "message": "UNAUTHORIZED",
      "name": "GDLError",
      "time_thrown": "2018-07-20T04:27:46.733Z",
      "data": {
        "resCode": "UNAUTHORIZED",
        "params": []
      }
    }
  ],
  "data": {
    "getSupportRequest": null,
    "getTotalSupportRequest":null,
    }
}`
But autual result:
`{
  "errors": [
    {
      "message": "UNAUTHORIZED",
      "name": "GDLError",
      "time_thrown": "2018-07-20T04:27:46.733Z",
      "data": {
        "resCode": "UNAUTHORIZED",
        "params": []
      }
    }
  ],
  "data": {
    "getSupportRequest": null,
    "getRequestTypeLookup": [
      {
        "id": "5b34a1ccdeca3966984d8f0a",
        "value": "aaaa"
      },
      {
        "id": "5b34a1ccdeca3966984d8f09",
        "value": "aaaa"
      },
      {
        "id": "5b34a1ccdeca3966984d8f08",
        "value": "aaaaa"
      },
      {
        "id": "5b34a1ccdeca3966984d8f07",
        "value": "aaaaa"
      },
      {
        "id": "5b34a1ccdeca3966984d8f06",
        "value": "aaaa"
      },
      {
        "id": "5b34a1ccdeca3966984d8f05",
        "value": "Thiếu hàng"
      },
      {
        "id": "5b34a1ccdeca3966984d8f04",
        "value": "aaaa"
      },
      {
        "id": "5b34a1ccdeca3966984d8f03",
        "value": "aaaa"
      },
      {
        "id": "5b34a1ccdeca3966984d8f02",
        "value": "aaaa"
      }
    ]
  }
}`

**Comment by maticzav** [comment]
@nmquaan would you mind sharing your schema as well? I believe I can better explain the solution on your concrete problem.

**Comment by nmquaan** [comment]
Hi @maticzav,
Thanks for your reply. I solved my problem 5 days ago.
I will close this issue now.
